### ISSUE TITLE
RadSideDrawer gestures make edge content hard to press on Android

### ISSUE THREAD

**Issue by interrobrian** [telerik/nativescript-ui-feedback#734] opened 2018-07-13 20:59 UTC
### Which platform(s) does your issue occur on?
Android

### Tell us about the problem
When using a RadSideDrawer with a NavigationButton (a common combination), the RadSideDrawer gesture interferes with the button. On Native SDK apps with the same layout, you can tap the exact first pixel of the screen to the left of the navigation button, and it will open the drawer. However, in NativeScript apps which use the same pattern, such as Examples NativeScript or the Drawer Navigation template, taps on the left side of the navigation button, even quite a ways in, get misinterpreted as the start of the drawer drag gesture. This causes a small part of the drawer to appear and disappear quickly. Instead, it should behave like typical Android apps and tap the navigation button, thus opening the drawer.

This bug also effects any other elements on the edge of the screen - Native SDK apps separate an edge tap vs swipe, but NativeScript apps with the RadSideDrawer flicker a small part of the drawer when the edge is tapped.

### Please provide the following version numbers that your issue occurs with:
- **Progress NativeScript UI version:** 4.1.1
- **CLI:** 4.1.0
- **Cross-platform modules:** 4.1.0
- **Runtime:** 4.1.

### Please tell us how to recreate the issue in as much detail as possible.
1. Open Examples NativeScript (or any NativeScript app using the RadSideDrawer + NavigationButton combination)
2. Tap just to the left of the menu icon in the top left

**Comment by tsonevn** [comment] 2018-07-16 11:54
Hi @interrobrian,
In NativeScirpt templates and sample application are using the required Android [UX guidelines](https://material.io/design/layout/responsive-layout-grid.html#columns-gutters-margins). Regarding that, we have set up the needed margins between components. Also, this required space seems to be responsible for this SideDrawer's behaviour.  Also, keep in mind that in NativeScript you can [disable the SideDrawer](https://docs.telerik.com/devtools/nativescript-ui/api/classes/radsidedrawer.html#gesturesenabled) gestures, which will allow the user to open the drawer, only by clicking on the NavigationButton.
If you still think that this is a bug, please provide more detailed info, which describes why this is a problem.

**Comment by interrobrian** [comment] 2018-07-16 16:51
Here are some gifs which demonstrate the problem, with the Android taps and pointer info visible. 

This is the Android Settings app. Other native SDK apps, such as Downloads or Calendar, follow this same behavior:
![Android Settings Drawer](https://i.imgur.com/zH8V4eX.gif)
Note that taps to the left of the drawer icon open the drawer. Similarly, other taps along the left edge of the screen are interpreted as taps.

This is the NativeScript "Drawer Navigation" template running with no modification. You can find the same behavior in the "Examples NativeScript" app:
![NativeScript Drawer Navigation](https://i.imgur.com/L1pbaWT.gif)
Note that taps to the left of the drawer icon make the drawer appear for a split second. This problem also extends to any other taps along the left edge, and not just the navigation button. This can be frustrating to users because they tap the screen and feel like nothing happens.

We have considered disabling the drawer gestures, but would prefer not to so that our app can behave as closely as possible to the Material [Navigation Drawer](https://material.io/design/components/navigation-drawer.html#modal-drawer).

**Comment by DimitarTodorov** [comment] 2018-08-01 06:57
The issue is fixed with the latest release of nativescript-ui-sidedrawer. 
https://github.com/NativeScript/nativescript-ui-sidedrawer/releases/tag/v4.2.1

**Closed by DimitarTodorov** 2018-08-01 06:57 UTC
Labels: backlog, os: android, ready for release, sidedrawer

**Comment by milejko** [comment] 2018-10-11 22:12
I don't think it is fixed right way. It is true, that now the sidedrawer is not "blinking", but gestures block tap events on very wide part of the screen. In fact turning off gestures is the only solution for now.

**Comment by Lehren** [comment] 2020-01-07 14:30
This issue is very annoying. Hoping for a fix.
