### ISSUE TITLE
Autocomplete - Need to change the text "No Results Found"

### ISSUE THREAD

**Issue by pablobitcode** [telerik/nativescript-ui-feedback#658] opened 2018-05-09 08:11 UTC
> Please take a minute to read our [NativeScript Code of Conduct](https://github.com/NativeScript/codeofconduct) before proceeding with posting issues or discussing. The purpose of this guide is to make communication and cooperation within our forums a pleasure for you and the other members.

### Did you verify this is a real problem by searching the [NativeScript Forum](https://discourse.nativescript.org/)?
Yes

### Tell us about the problem
I can't find a method to change the text "No Results Found" using nativescript-ui-autocomplete.
Need to change the text and translate it to multiple languages later, but can't access it.

### Which platform(s) does your issue occur on?
Both

### Please provide the following version numbers that your issue occurs with:
- **Progress NativeScript UI version:** 3.6.0
- **CLI:** 3.4.2
- **Cross-platform modules:** 3.4.0
- **Runtime(s):** 3.4.2

### Please tell us how to recreate the issue in as much detail as possible.
1. Start the application
2. Write a band that doesn't exist in the autocomplete field
3. "No results Found" text appears

### Is there code involved? If so, please share the minimal amount of code needed to recreate the problem.
https://play.nativescript.org/?template=play-js&id=a1dOUf&v=3

**Comment by stephanegg** [comment] 2018-05-15 22:04
Please try below code, you can do the same with android:

`import { AutoCompleteEventData, RadAutoCompleteTextView } from 'nativescript-ui-autocomplete';`
`import { ios as iosApp } from 'tns-core-modules/application';`

`customAutocomplete(args: AutoCompleteEventData) {`
    `const autocomplete = <RadAutoCompleteTextView>args.object;`
    `if (iosApp) {`
        `const radIOS = autocomplete.ios;`
        `radIOS.noResultsLabel.text = "Custom no results";`
    `}` 
`}`

**Comment by pablobitcode** [comment] 2018-05-16 06:50
Hi Stephanegg,

Your solution works like a charm for ios, thank you for that!
Unfortunately, android version doesn't have "noResultsLabel" and therefore, cant access the error message to change the text :/

**Comment by naranjja** [comment] 2018-05-24 00:39
Hi @stephanegg,

I have to second @pablobitcode. Android does not have said `noResultsLabel` and this is not documented. Do you know how to edit this text in Android?

Thanks!

**Comment by zbranzov** [comment] 2018-08-08 07:52
The feature is released in nativescript-ui-autocomplete@3.8.0

**Closed by zbranzov** 2018-08-08 07:52 UTC
Labels: autocomplete, feature, ready for release

**Comment by felix-idf** [comment] 2019-02-06 14:08
the issue is closed, but I cannot see anything in the docs about how to change the "no results found" label.
Can anyone help me?

**Comment by tgpetrov** [comment] 2019-02-07 07:22
@felix-idf 
Changing this label is demonstrated in the [samples](https://github.com/telerik/nativescript-ui-samples/blob/master/autocomplete/app/examples/customization/autocomplete-customization-page.xml#L4) and [samples-angular](https://github.com/telerik/nativescript-ui-samples-angular/blob/master/autocomplete/app/examples/customization/autocomplete-customization.component.html#L3).

**Comment by felix-idf** [comment] 2019-02-07 07:32
@tgpetrov thanks
