### ISSUE TITLE
A way to pass the data to the CalendarEvent model

### ISSUE THREAD

**Issue by davidjiangAR** [telerik/nativescript-ui-feedback#588] opened 2018-03-27 03:13 UTC
### Tell us about the problem
There are some events in the Calendar. We need the parameters such as id to open the detail page once user tap the event. I have added a class to extend the CalendarEvent model and added the id property , use this model to store the event data and binding the model list to RadCalendar. However, i cannot get the id property in the event data of the CalendarInlineEventSelectedData after tap the event. It seems the RadCalendar created a new CalendarEvent model and pass it to CalendarInlineEventSelectedData. Could you please let me know if there is a way to pass the data to the CalendarEvent model?

Here is my codes:

the new Class extends the CalendarEvent

import { CalendarEvent } from "nativescript-pro-ui/calendar";
import { Color } from "color";
export class CalendarEventModel extends CalendarEvent{
    _planId:string;
    constructor(planId:string,title: string, startDate: Date, endDate: Date, isAllDay?: boolean, eventColor?: Color){
        super(title,startDate,endDate,isAllDay,eventColor);
        this._planId=planId;
    }

}

add event model:

let event = new CalendarEventModel(item.id, item.name +"/"+item.id, eventStartDate, eventEndDate, false, new Color("Black"));
this._events.push(event);

### Which platform(s) does your issue occur on?
IOS

**Comment by davidjiangAR** [comment] 2018-04-20 02:55
Hi,

 Any update for this question?

**Comment by tgpetrov** [comment] 2018-04-27 15:48
Duplicate of: https://github.com/telerik/nativescript-ui-feedback/issues/418

**Closed by tgpetrov** 2018-04-27 15:48 UTC
