### ISSUE TITLE
RadListView StaggeredLayout left column is empty when setting the layout programmatically

### ISSUE THREAD

**Issue by Tyg-g** [telerik/nativescript-ui-feedback#725] opened 2018-07-07 21:17 UTC
### Did you verify this is a real problem by searching the [NativeScript Forum](https://discourse.nativescript.org/)?
Yes

### Tell us about the problem
RadListView StaggeredLayout left column is empty when setting the layout programmatically

### Which platform(s) does your issue occur on?
Android

### Please provide the following version numbers that your issue occurs with:
CLI: 4.1.0
Cross-platform modules: 4.1.0
Runtime(s): "tns-android": {"version": "4.1.2"}
Plugin(s):

    "dependencies": {
        "events": "^3.0.0",
        "nativescript-localstorage": "^1.1.5",
        "nativescript-theme-core": "^1.0.4",
        "nativescript-ui-listview": "^3.5.8",
        "parse": "^1.11.1",
        "tns-core-modules": "^4.1.0"
    },
    "devDependencies": {
        "babel-traverse": "~6.26.0",
        "babel-types": "~6.26.0",
        "babylon": "~6.18.0",
        "lazy": "~1.0.11"
    }

### Please tell us how to recreate the issue in as much detail as possible.
Create a RadListView and set the layout programmatically to StaggeredLayout. I see then that the left column is empty. However this is not the case when I set the Layout in the XML.

![screenshot_20180707_230832](https://user-images.githubusercontent.com/40174710/42414714-81e17674-823b-11e8-9195-b0ea5ab898fd.png)
![screenshot_20180707_230929](https://user-images.githubusercontent.com/40174710/42414717-8d2acaee-823b-11e8-8e43-0c8ff21f433a.png)
![screenshot_20180707_231004](https://user-images.githubusercontent.com/40174710/42414720-9c917e10-823b-11e8-8341-66b8f28c6590.png)

### Is there code involved? If so, please share the minimal amount of code needed to recreate the problem.

    const RadListView = require("nativescript-ui-listview");
    var layout = new RadListView.ListViewStaggeredLayout();
    layout.scrollDirection = 'vertical';
    layout.spanCount = 2;
    myRadListView.listViewLayout = layout;

**Comment by VladimirAmiorkov** [comment] 2019-02-27 11:38
Hi,

It has been some time since this issue was created. We apologize for the late response, could you veryfiy if this issue is still present in the latest version 5.2.0 of nativescript-ui-listview. Also please see our "Change at runtime example" that shows how you can change the layout of the RadListView at runtime [here](https://github.com/telerik/nativescript-ui-samples/blob/master/listview/app/examples/item-layouts/item-layouts-runtime-page.ts).

**Comment by VladimirAmiorkov** [comment] 2019-02-27 11:39
For now I will close this issue as we are not able to reproduce it on our side. If continue to hit such issue please let us know and send us a sample project or a playground link.

**Closed by VladimirAmiorkov** 2019-02-27 11:39 UTC
Labels: listview
