### ISSUE TITLE
[Bug report] Easy Crash to cause using scrollToIndex

### ISSUE THREAD

**Issue by NickIliev** [telerik/nativescript-ui-feedback#29] opened 2016-11-11 07:52 UTC
> I see this crash frequently (started wrapping it in a try/catch); but if you do RLV.scrollToIndex(x) it can frequently crash when the component is still being internally setup.  (From my point of view and NS's point of view the ._android exists; but apparently, internally you aren't fully configured and this should get fixed so that it doesn't crash...

 

> I have two places that I can normally see it; it seems to be _timing_ related.   Because it doesn't always crash.
> 1. On orientation change, was the report from yesterday -- I used my last saved location and attempted to reset it back.
> 2. On NavigatedTo event, shortly after doing a listview.refresh (I believe the refresh is the cause).   

 

```
W/System.err( 7454): Error: java.lang.Exception: Failed resolving method scrollToPosition on class com.telerik.widget.list.RadListView
W/System.err( 7454):     com.tns.Runtime.resolveMethodOverload(Runtime.java:983)
W/System.err( 7454):     com.tns.Runtime.callJSMethodNative(Native Method)
W/System.err( 7454):     com.tns.Runtime.dispatchCallJSMethodNative(Runtime.java:1022)
W/System.err( 7454):     com.tns.Runtime.callJSMethodImpl(Runtime.java:907)
W/System.err( 7454):     com.tns.Runtime.callJSMethod(Runtime.java:895)
W/System.err( 7454):     com.tns.Runtime.callJSMethod(Runtime.java:879)
W/System.err( 7454):     com.tns.Runtime.callJSMethod(Runtime.java:871)
```

Reported from @NathanaelA

**Comment by VladimirAmiorkov** [comment] 2016-11-14 13:31
Hi @NickIliev , @NathanaelA

Thank you for reporting this to us. I will take a look at let you know, in the meanwhile you mentioned that this issue is happening in two specific scenarios, when changing the orientation and on navigation, do you have a sample project that you can share with me as of this moment. This will help in reproducing the exact approach that leads to this issue.

**Comment by NathanaelA** [comment] 2016-11-14 18:32
@VladimirAmiorkov - Sorry, this is a clients app; and I don't believe he wants it to be distributed anywhere yet.   
A Couple notes:  This is Android, I don't think it has ever crashed in the iOS version.
Basically just attach to the rotation event and then attempt to reassign the position in the event handler....
The other place is assign the data, then try and set the scroll position will typically crash it...

**Comment by VladimirAmiorkov** [comment] 2016-11-24 12:19
Hi @NickIliev @NathanaelA ,

After looking into this report further I was not able to reproduce the mentioned behavior when calling the RadListView's scrollToIndex() method in the orientationChangedEvent of the application in both vanilla and {N} + Angular applications. Can you share more specific code of your implementation for further research. Here you can find code snippets of what my test involved which both work as expected when the device is rotated:

- {N} + Angular:
```
import { Component, OnInit, ChangeDetectorRef, ViewChild } from "@angular/core";
...
import { Page } from "ui/page";
import { RadListView } from "nativescript-telerik-ui-pro/listview";
import { RadListViewComponent } from "nativescript-telerik-ui-pro/listview/angular";
import * as applicationModule from 'application';

@Component({
    moduleId: module.id,
    selector: "tk-listview-item-loading",
    template:`
    <GridLayout>
          <RadListView #myListView [items]="dataItems">
               <template tkListItemTemplate let-item="item">
                      <Label class="nameLabel" [text]="item.name"></Label>
                </template>
           </RadListView>
     </GridLayout>`,
})
export class ListviewItemLoadingComponent implements OnInit {
    private _dataItems: ObservableArray<DataItem>;
    private _listView: RadListView;

    constructor(private _page: Page, private _changeDetectionRef: ChangeDetectorRef) {
        this._page.on("loaded", this.onLoaded, this);
        this._page.on("unloaded", this.onUnloaded, this);
    }

    @ViewChild("myListView") myListView: RadListViewComponent;

    private onLoaded() {
        applicationModule.on(applicationModule.orientationChangedEvent, this.setOrientation, this);
        this.myListView.listView.scrollToIndex(9);
    }

    private onUnloaded() {
        applicationModule.off(applicationModule.orientationChangedEvent, this.setOrientation, this);
    }

    ngOnInit() {
        this._dataItems = new ObservableArray<DataItem>(); 
        // get items
        this._changeDetectionRef.detectChanges();
    }

    private setOrientation(args) {
        console.log(">>>> orientation changed newValue: " + args.newValue);
        this.myListView.listView.scrollToIndex(87);
    }
}
```

- Vanila {N}

XML:
<Page loaded="onPageLoaded" xmlns:lv="nativescript-telerik-ui-pro/listview" xmlns="http://www.nativescript.org/tns.xsd">
    <GridLayout orientation="vertical" rows="auto, *, auto" >
        <lv:RadListView id="listView" items="{{ dataItems }}" row="1" itemLoading="onItemLoading">
            <lv:RadListView.itemTemplate>
                <StackLayout orientation="vertical" padding="15">
                    <Label fontSize="20" text="{{ itemName }}" marginBottom="10"/>
                </StackLayout>
            </lv:RadListView.itemTemplate>
        </lv:RadListView>
    </GridLayout>
</navigation:ExamplePage>

TypeScript:

```
import { RadListView } from "nativescript-telerik-ui-pro/listview";
import * as applicationModule from 'application';

export function onPageLoaded(args) {
    var page = args.object;
    listView = page.getViewById("listView");
    ...
    applicationModule.on(applicationModule.orientationChangedEvent, setOrientation, this);
}

export function setOrientation(args) {
    console.log(">>>> orientation changed newValue: " + args.newValue);
    listView.scrollToIndex(87);
}
```

**Comment by NathanaelA** [comment] 2016-11-24 23:21
Since you have the sample app; can you try putting a `listView.refresh();` before the `listview.scrollToIndex(87);` in the `setOrientation` function and see if that causes it...

**Comment by VladimirAmiorkov** [comment] 2016-11-29 15:07
Hi @NathanaelA ,

Adding the call to the refresh() method also does not lead to the described exception. [Here](http://www.screencast.com/t/7GQq29pdtyg) you can find a short video showing how the RadListView's scrollToIndex + refresh methods work in both Page's navigatedTo and Application's orientationChanged events. The video uses the previously mentioned source code plus a call to the `refresh()` just before the `scrollToIndex()`

```
export function orientationChanged(args) {
    console.log(">>>> orientationChanged newValue: " + args.newValue);
    listView.refresh();
    listView.scrollToIndex(87);
}
```

If you can share a working application which experiences this issue it would be very helpful, unfortunately without being able to observe it on our side we cannot provide you with a solution.

**Comment by NathanaelA** [comment] 2016-11-29 18:34
Hmm, I can't share the application but we can go through the routine that is causing the issue in depth...  I've attempted to strip out anything that is unrelated to the list view...

```
exports.orientation = function(args) {
    var isLandscape = args.landscape;
    
    if (isLandscape) {
        listView.listViewLayout.scrollDirection = "Horizontal";
    } else {
        listView.listViewLayout.scrollDirection = "Vertical";
    }
    try {
        if (currentItem > 0) {
            listView.scrollToIndex(currentItem);
        }
    } catch (err) {
        // eat the crashing error...
    }

};

```

After removing ios only code and other non-list view code -- Looking at this maybe the issue is this:
       ``` listView.listViewLayout.scrollDirection = "Vertical"; ``` & ```        listView.listViewLayout.scrollDirection = "Horizontal";```

  I switch scroll direction on orientation change, maybe this causes your listview to be in a weird state by the time the scrollToIndex is called.   Again this only occurs on Android, and you can see from the call stack in the first message it is in your code where it crashes.

**Comment by VladimirAmiorkov** [comment] 2016-11-30 11:36
@NathanaelA 

I did try to reproduce it with this additional information but again to no avail. The expected behavior of changing the layout orientation + refreshing + scrolling to and index is executed correctly.

I created a sample test project for you and attached it to my response, could you try to run in and see if it is ok on your end?

[listview-scroll.zip](https://github.com/telerik/nativescript-ui-feedback/files/621661/listview-scroll.zip)

**Comment by NathanaelA** [comment] 2016-11-30 18:09
Thanks, I'll try it and see if it crashes for me...

**Closed** 2017-03-06 12:50 UTC
Labels: listview, needs more info
