### ISSUE TITLE
RadListView do not show images on iOS

### ISSUE THREAD

**Issue by stoskov** [telerik/nativescript-ui-feedback#842] opened 2018-09-19 11:18 UTC
### Did you verify this is a real problem by searching the [NativeScript Forum](https://discourse.nativescript.org/)?
Yes

### Tell us about the problem
Items' images not visible on iOS. It works fine on Android.

### Which platform(s) does your issue occur on?
iOS

### Please provide the following version numbers that your issue occurs with:
- **nativescript-ui-listview:** "3.5.11"
- **CLI:** it is in {N} Playground
- **Cross-platform modules:**   4.2.0
- **Runtime(s):** 4.2.0

### Please tell us how to recreate the issue in as much detail as possible.

Test the following code in {N} Playground with random collection

```
<GridLayout backNavigation>
	<RadListView *ngIf="(myItems | async) as items" [items]="items">
		<ng-template let-item="item">
			<StackLayout padding="10" (tap)="onItemTap(item)">
				<Image src="https://play.nativescript.org/dist/assets/img/NativeScript_logo.png"></Image>
				<Label text="Label"></Label>
			</StackLayout>
		</ng-template>
	</RadListView>
</GridLayout>
```

On Android each row has image and label under it. On iOS only the label is displayed

![img_9176](https://user-images.githubusercontent.com/2779206/45750226-e27dd580-bc16-11e8-9d42-60a63dee251a.jpg)

**Comment by lini** [comment] 2018-09-21 11:41
Duplicate of https://github.com/telerik/nativescript-ui-feedback/issues/447

To fix:
- set width/height of the image
- refresh the RadListView programmatically after the images are downloaded from the internet so the correct sizes are applied - `listview.refresh()`

**Closed by lini** 2018-09-21 11:41 UTC
Labels: bug, listview, os: ios, severity: high
