### ISSUE TITLE
Error when trying to bind data on my radlistview

### ISSUE THREAD

**Issue by dgmaar** [telerik/nativescript-ui-feedback#270] opened 2017-08-19 18:43 UTC
### Did you verify this is a real problem 
Yes

### Tell us about the problem
this issue appears when trying to set data on one of my radlistview, I'm using two radlistview on my page.

*** Assertion failure in -[TKCollectionView _endItemAnimationsWithInvalidationContext:tentativelyForReordering:animator:], /BuildRoot/Library/Caches/com.apple.xbs/Sources/UIKit_Sim/UIKit-3600.7.47/UICollectionView.m:5781
Aug 19 13:37:04 dulces-iMac com.apple.CoreSimulator.SimDevice.CA5F5C9C-1B9F-4AC1-90E5-D25E7DD049A1.launchd_sim[6335] (UIKitApplication:mx.sicar.sicarapp[0x6a03][6357][10508]): Service exited due to Segmentation fault: 11

### Which platform(s) does your issue occur on?
iOS

### Please provide the following version numbers that your issue occurs with:

 nativescript     │ 3.1.3           │ 3.1.3   
 tns-core-modules │ 3.1.1           │ 3.1.1      
 tns-android      │ 3.1.1           │ 3.1.1         
 tns-ios          │ 3.1.0           │ 3.1.0

**Comment by ginev** [comment] 2017-08-21 06:48
@dgmaar - to be able to better assist we would need some more information about the way you are fetching your data and assigning it to RadListView. Can you please share some source here?

**Comment by tsonevn** [comment] 2017-12-06 14:10
closing due to inactivity

**Comment by felix-idf** [comment] 2018-03-07 15:39
@tsonevn @ginev  I get exactly this error message, you can have a look at the following sample project:

**Comment by tsonevn** [comment] 2018-03-08 12:28
Hi @felix-idf,
Thank you for the sample project.
I tested it on my side, however, the application was build successfully and the binding works as expected after secondary navigation. 

Can you check if you are using the latest version of NativeScript CLI 3.4.2? Also, try removing the platform with `tns platform remove android` and delete `node_modules` folder. Then rebuild the app `tns run android`.

**Comment by felix-idf** [comment] 2018-03-08 12:55
Hi @tsonevn ,
thank you for your fast reply.

As @dgmaar already mentioned in this thread, the problem is the iOS platform, not Android (everything works as expected there).

I have NativeScript **3.4.3** installed and I tested this with the iOS simulator: **iPhone 6 - iOS 10.3.1**.

The following GIF shows steps 3 and 4 of the described scenario until the app crashes:
![assertion](https://user-images.githubusercontent.com/6443021/37152056-45e512ba-22d8-11e8-8be8-2d048cce8e79.gif)

> *** Assertion failure in -[TKCollectionView _endItemAnimationsWithInvalidationContext:tentativelyForReordering:animator:], /BuildRoot/Library/Caches/com.apple.xbs/Sources/UIKit_Sim/UIKit-3600.7.47/UICollectionView.m:5569

**Comment by felix-idf** [comment] 2018-03-08 15:13
Thanks for re-opening this issue.

I noticed, that the [sample app](https://github.com/telerik/nativescript-ui-samples), the databinding is done a different way:

The viewmodel is is a class that extends the Observable class and you assign a new instance of this ViewModel class as the bindingContext of the page each time in the navigatingTo event of the page.
This way, the error does not occur on iOS...

Apart from the fact, that it would be a huge amount of work to re-write the Viewmodel machanism for all pages in our app, I think it is not resource-friendly to create a new instance of the ViewModel class everytime you navigate to a page, instead of re-using an existing object.

I hope there is another way to overcome this issue.

**Comment by anuragd7** [comment] 2018-03-19 10:31
Hi, Iam facing a similar issue in my nativescript angular project too. The rad list view loads fine, but when I try to delete an item from the list view it fails with the error - *** Assertion failure in -[TKCollectionView _endItemAnimationsWithInvalidationContext:tentativelyForReordering:animator:], /BuildRoot/Library/Caches/com.apple.xbs/Sources/UIKit_Sim/UIKit-3600.9.1/UICollectionView.m:5569.

Any fixes/ solutions would be highly appreciated.

**Comment by shivgolani** [comment] 2018-05-25 19:10
Hello @fakalieva replacing navigatingTo with loaded resolves the bug.

**Closed** 2018-06-18 11:56 UTC
Labels: backlog, bug, listview, os: ios, ready for release, severity: high
