### ISSUE TITLE
AutoCompleteTextView duplicates token when navigating back to view (Android)

### ISSUE THREAD

**Issue by rdlauer** [telerik/nativescript-ui-feedback#443] opened 2017-12-07 19:46 UTC
### Tell us about the problem
On Android only (iOS works fine), if you add a token to your AutoCompleteTextView, navigate away from the view, and return to the view, the token will be there twice.

### Which platform(s) does your issue occur on?
Android only

### Please provide the following version numbers that your issue occurs with:
- **Progress NativeScript UI version:** 3.2.0
- **CLI:** 3.3.1
- **Cross-platform modules:** 3.3.1
- **Runtime(s):** 3.3.0

### Please tell us how to recreate the issue in as much detail as possible.
1. [Clone this repo](https://github.com/rdlauer/ui-for-nativescript-autocompletetextview)
2. Perform the steps shown in this gif:

![untitled](https://user-images.githubusercontent.com/1918280/33735452-f0f3b63c-db54-11e7-847a-58f0e815d3db.gif)

**Comment by VladimirAmiorkov** [comment] 2018-02-05 09:20
Hi @rdlauer ,

Thank you for reporting this to us. I can confirm that it is issue in the current version of the plugin. I am taking a look at it as we speak and update you once I have more information.

**Comment by rdlauer** [comment] 2018-05-09 02:36
I finally got around to testing this after upgrading to 4.0 and `nativescript-ui-autocomplete` to 3.7.0:

✔ Component nativescript has 4.0.0 version and is up to date.
✔ Component tns-core-modules has 4.0.0 version and is up to date.
✔ Component tns-android has 4.0.1 version and is up to date.
✔ Component tns-ios has 4.0.1 version and is up to date.

I'm finding the exact same problem exists on Android, with the token being added to the display when navigating back.

**Comment by VladimirAmiorkov** [comment] 2018-05-09 07:52
Hi @rdlauer ,

I managed to reproduce this issue with the current version of nativescript-ui-autocomplete and I will reopen it. It looks like there is an additional issue that was not initially resolved leading to the same issue in additional scenarios.

**Comment by zbranzov** [comment] 2018-08-08 07:53
The fix is released in nativescript-ui-autocomplete@3.8.0

**Closed by zbranzov** 2018-08-08 07:53 UTC
Labels: autocomplete, backlog, bug, os: android, ready for release, severity: medium
