### ISSUE TITLE
[Q] RadSideDrawer: Components not loading, drawer disappearing

### ISSUE THREAD

**Issue by waszqba** [telerik/nativescript-ui-feedback#668] opened 2018-05-18 07:50 UTC
> Please take a minute to read our [NativeScript Code of Conduct](https://github.com/NativeScript/codeofconduct) before proceeding with posting issues or discussing. The purpose of this guide is to make communication and cooperation within our forums a pleasure for you and the other members.

## Please, provide the details below:
Hi, I have a rather unusual situation here. I was trying to implement application-wide sideDrawer component and used the appropriate directive on `<page-router-outlet>` and several issues occurred.

At first, in this configuration I get a sideDrawer draggable from left, but absolutely no content of any component loaded on start via router (besides the action bar, this thing never dies).

When I try to use the directive on a stacklayout and put the router outlet inside of it, then I get my desired contents and even the sideDrawer is able to be opened by swiping from left. However, when I navigate to any other page (using angular router), the sideDrawer is no longer available and cannot be opened by swiping from left, which also happens with the first case (using button from action bar).

Also, whatever the use case may be, I cannot refer to the drawer any way mentioned in the examples or tutorials. I get a frame, but it doesn't have any sideDrawer related methods.

The sad thing is, when I try to recreate the problem using a fresh template from sideKick or on playground, everything works like a charm, so I assume there's a conflict in my project.

With all that said, I'd like to ask for some clues, what to look for, where to look for it. I even tried to create fresh components inside my project and arrange them exactly as in the attached playground project, but no luck :(

### Did you verify this is a real problem by searching the [NativeScript Forum](https://discourse.nativescript.org/)?
_Yes_

### Which platform(s) does your issue occur on?
_Android_

### Please provide the following version numbers that your issue occurs with:
- **Progress NativeScript UI version:** 4.1.0 (`nativescript-ui-sidedrawer`)
- **CLI:** 4.0.0
- **Cross-platform modules:** 4.0.0
- **Runtime(s):** 4.0.1 for both

### Please tell us how to recreate the issue in as much detail as possible.
1. Start the application ..
2. open and close sidedrawer
3. navigate to other page
4. ???
5. profit

### Is there code involved? If so, please share the minimal amount of code needed to recreate the problem.
[here](https://play.nativescript.org/?template=play-ng&id=hqcfqm&v=9)

**Comment by tsonevn** [comment] 2018-05-21 12:28
Hi @waszqba,
I tested the Playground project on my side, however, I am unable to recreate the issue. Can you sen us the project, where this problem is reproducible. This will help in researching what is causing the issue.

**Comment by waszqba** [comment] 2018-05-23 07:16
Hi @tsonevn, unfortunately, I cannot send you the exact project I'm facing the issue in, however I've managed to workaround the issue with a component with sidedrawer which takes some `ng-content` in, so I just could wrap my main components in this solution, however it's not working as the global one. I will try to recreate the issue asap. Meantime, maybe there's something wrong with package versions I'm using? Here's my dependencies' excerpt from `package.json`:
```
"@angular/animations": "~5.2.0",
    "@angular/common": "~5.2.0",
    "@angular/compiler": "~5.2.0",
    "@angular/core": "~5.2.0",
    "@angular/forms": "~5.2.0",
    "@angular/http": "~5.2.0",
    "@angular/platform-browser": "~5.2.0",
    "@angular/platform-browser-dynamic": "~5.2.0",
    "@angular/router": "~5.2.0",
    "lodash": "^4.17.5",
    "nativescript-angular": "~5.2.0",
    "nativescript-feedback": "^1.1.2",
    "nativescript-floatingactionbutton": "^4.1.3",
    "nativescript-social-share": "^1.5.0",
    "nativescript-theme-core": "~1.0.4",
    "nativescript-ui-autocomplete": "^3.6.0",
    "nativescript-ui-chart": "^3.5.0",
    "nativescript-ui-listview": "^3.5.1",
    "nativescript-ui-sidedrawer": "^4.1.0",
    "reflect-metadata": "~0.1.10",
    "rxjs": "~5.5.5",
    "tns-core-modules": "^4.0.0",
    "zone.js": "~0.8.18"
```

**Comment by NickIliev** [comment] 2018-06-21 12:52
@waszqba I am closing the issue as we can't reproduce it. If possible please isolate the issue in template project and I will reopen for further investigation

**Closed by NickIliev** 2018-06-21 12:52 UTC
Labels: needs more info, sidedrawer

**Comment by ali4fun** [comment] 2019-09-19 15:10
it again happened in NS6. this page-router-outlet making problem to load other UI elements. in first attempt it make page full screen after move between component it load UI elements. 
why this not load all UI element in first attempt ?
how can I solve this issue ?
