### ISSUE TITLE
[RadListView] Issue with setting up itemInsertAnimation property via XML

### ISSUE THREAD

**Issue by tsonevn** [telerik/nativescript-ui-feedback#202] opened 2017-06-05 11:05 UTC
Setting up the itemIserAnimation property via XML will not apply the Animation. This issue is reproducible on Android while using latest official UI for NativeScript `2.0.1` and `@next`.

### Which platform(s) does your issue occur on?
> Android

### Please provide the following version numbers that your issue occurs with:
- **Progress NativeScript UI version:** 2.0.1
- **CLI:** 3.0.1
- **Cross-platform modules:** 3.0.0

### Is there code involved? If so, please share the minimal amount of code needed to recreate the problem.
For example:
```
<lv:RadListView loaded="lvloaded" items="{{ dataItems }}"  id="ls" >
            <lv:RadListView.listViewLayout>
                 <lv:ListViewLinearLayout scrollDirection="Vertical" itemInsertAnimation="Slide" itemDeleteAnimation="Default"/>
            </lv:RadListView.listViewLayout>
            <lv:RadListView.itemTemplate>
                <StackLayout orientation="vertical">
                    <Label fontSize="20" text="{{ _itemName }}"/>
                    <Label fontSize="14" text="{{ _itemDescription }}"/>
                </StackLayout>
            </lv:RadListView.itemTemplate>
         </lv:RadListView>
```

**Comment by VladimirAmiorkov** [comment] 2017-06-06 14:14
After further investigation I was not able to reproduce the issue on my side. It looks like the sdk example "Item Animations" itself has a [hidden](https://github.com/telerik/nativescript-ui-samples/blob/release/sdk/app/listview/item-animations/item-animations.ts#L17) "feature" that resets the XML value to "Default" .

Closing this issue because setting `itemInsertAnimation="Slide"` `itemDeleteAnimation="Slide" ` after removing the mentioned code from the example resolves the issue.

**Closed by VladimirAmiorkov** 2017-06-06 14:14 UTC
Labels: bug, listview
