### ISSUE TITLE
change fillcolor of indicator from js code (Gauge)

### ISSUE THREAD

**Issue by giorgi-abashidze** [telerik/nativescript-ui-feedback#688] opened 2018-06-06 08:57 UTC
I want to change fillcolor of indicator depending on data,

```
let gaugeView = page.getViewById("gaugeView");
let scale = gaugeView.scales.getItem(0);
let barIndicator = scale.indicators.getItem(0);
barIndicator.indicatorStyle.fillColor='#008489';
```
after this when I log fillColor of indicator I see its changed but in the view there is still old color

there is no redraw or refresh?

**Comment by tsonevn** [comment] 2018-06-06 10:05
Duplicate of #639

**Closed by tsonevn** 2018-06-06 10:05 UTC
