### ISSUE TITLE
Exception in thread "main" java.lang.ClassNotFoundException: Class: com.telerik.android.primitives.widget.sidedrawer.DrawerChangeListener

### ISSUE THREAD

**Issue by JakhubJiricka** [telerik/nativescript-ui-feedback#981] opened 2019-01-06 13:53 UTC
after run "tns plugin add nativescript-ui-sidedrawer" in my angular native project I got this error.

Exception in thread "main" java.lang.ClassNotFoundException: Class: com.telerik.android.primitives.widget.sidedrawer.DrawerChangeListener
        at org.nativescript.staticbindinggenerator.Generator.getClass(Generator.java:776)
        at org.nativescript.staticbindinggenerator.Generator.collectInterfaceMethods(Generator.java:703)
        at org.nativescript.staticbindinggenerator.Generator.getPublicApi(Generator.java:227)
        at org.nativescript.staticbindinggenerator.Generator.writeBinding(Generator.java:342)
        at org.nativescript.staticbindinggenerator.Generator.generateBinding(Generator.java:133)
        at org.nativescript.staticbindinggenerator.Generator.processRows(Generator.java:172)
        at org.nativescript.staticbindinggenerator.Generator.generateBindings(Generator.java:90)
        at org.nativescript.staticbindinggenerator.Generator.writeBindings(Generator.java:66)
        at org.nativescript.staticbindinggenerator.Main.main(Main.java:47)

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:runSbg'.
> Process 'command 'C:\Program Files\Java\jdk1.8.0_191\bin\java.exe'' finished with non-zero exit value 1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 31s
Unable to apply changes on device: emulator-5554. Error is: Command gradlew.bat failed with exit code 1.
Executing after-watch hook from F:\Upwork\2019\01_02\instaq\hooks\after-watch\nativescript-dev-typescript.js
Stopping tsc watch
Executing after-watch hook from F:\Upwork\2019\01_02\instaq\hooks\after-watch\nativescript-dev-webpack.js
Stopping webpack watch
Executing after-watch hook from F:\Upwork\2019\01_02\instaq\hooks\after-watch\nativescript-dev-typescript.js
Executing after-watch hook from F:\Upwork\2019\01_02\instaq\hooks\after-watch\nativescript-dev-webpack.js
Stopping webpack watch

**Comment by tsonevn** [comment] 2019-01-07 11:46
Hi @JakhubJiricka,
Can you provide some more info about your environment(NativeScript CLI, tns-core-modules, tns-android versions)? Also, it will help if you send us the project and the exact steps, that you are using for building it. 
Meanwhile, you can try to clear up the project while following the below-attached steps:
1. delete `node_modules`, `platforms`, `hooks` folders and `package-lock.json` file
2. run `npm i`
3. rebuild the project -> `tns run android`

**Comment by DeniseCP** [comment] 2019-01-14 17:19
@tsonevn I am having the same problem. I just added the package and as soon as I did it started giving me this error.

`tns plugin add nativescript-ui-sidedrawer`

I have also retarted my machine, you never know, cleaned the hooks, platforms and node_modules, as you have indicated up there, but no success. I am running the project using  Node 10.15.0 and npm 6.5.0

When I run my project I usually run with `tns debug android` but I have tried `run` too, and no success.

After I cleaned I got this alert down below, should I be worried? : 
```
(node:15884) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
```

``` 
"tns-android": {
            "version": "5.1.0"
        },
        "tns-ios": {
            "version": "5.1.0"
        }

   
 "dependencies": {
        "@angular/animations": "~7.1.0",
        "@angular/common": "~7.1.0",
        "@angular/compiler": "~7.1.0",
        "@angular/core": "~7.1.0",
        "@angular/forms": "~7.1.0",
        "@angular/http": "~7.1.0",
        "@angular/platform-browser": "~7.1.0",
        "@angular/platform-browser-dynamic": "~7.1.0",
        "@angular/router": "~7.1.0",
        "@ngx-translate/core": "^11.0.1",
        "@ngx-translate/http-loader": "^4.0.0",
        "email-validator": "^2.0.4",
        "loadsh": "0.0.3",
        "nativescript-angular": "~7.1.0",
        "nativescript-https": "^1.0.3",
        "nativescript-theme-core": "^1.0.4",
        "nativescript-ui-sidedrawer": "^5.1.0",
        "reflect-metadata": "~0.1.8",
        "rxjs": "~6.3.0",
        "tns-core-modules": "~5.1.0",
        "tns-platform-declarations": "^5.1.1",
        "tslint": "^5.12.0",
        "zone.js": "^0.8.26"
    },
    "devDependencies": {
        "@nativescript/schematics": "~0.4.0",
        "nativescript-dev-typescript": "~0.7.0",
        "nativescript-dev-webpack": "~0.18.0",
        "@angular/compiler-cli": "~7.1.0",
        "@ngtools/webpack": "~7.1.0"
    },
```

**Comment by Triuman** [comment] 2019-01-19 18:06
Did you solved this problem? I added the side drawer plugin and getting the same error.
`tns plugin add nativescript-ui-sidedrawer`

**Comment by tsonevn** [comment] 2019-01-21 07:33
Hi @Triuman,
Can you send us a project, that can be used for debugging?

**Comment by Triuman** [comment] 2019-01-21 08:38
I solved the problem somehow and I have no idea how. Thank you.

**Comment by tsonevn** [comment] 2019-01-28 13:40
Hi all,
Following the last comments, I am assuming that the issue is resolved and we can close it. If the problem appears again and we have a stable way to recreate it, I will reopen it.

**Closed by tsonevn** 2019-01-28 13:40 UTC
Labels: needs more info

**Comment by manojchandrashekar** [comment] 2019-02-13 12:36
This worked for me: `tns run --clean android --bundle`

**Comment by Taking1n1** [comment] 2019-09-30 01:08
My problem was I installed nativescript-ui-sidedrawer on devDependencies instead of normal dependencies. Once I uninstalled and installed to dependencies it worked.
