### ISSUE TITLE
"bindingContext" of "swipe" View is not correct when grouping, filtering and/or sorting is enabled

### ISSUE THREAD

**Issue by VladimirAmiorkov** [telerik/nativescript-ui-feedback#803] opened 2018-08-23 14:26 UTC
After adding assigning the `tap` event to an element inside the `itemSwipeTemplate` accessing its object's bindingContext in order to get the "data object" of the swiped item returns the first item of the bound to the items collection rather than the actual data object.

**Comment by zbranzov** [comment] 2018-08-31 11:57
The issue is already fixed in nativescript-ui-listview@3.6.1. Enjoy!

**Closed by zbranzov** 2018-08-31 11:57 UTC
Labels: listview, ready for release
