### ISSUE TITLE
RadListView notifyPullToRefreshFinished not working sometimes

### ISSUE THREAD

**Issue by bhavincb** [telerik/nativescript-ui-feedback#647] opened 2018-05-04 14:25 UTC
[https://play.nativescript.org/?template=play-ng&id=zWAV8w&v=2](https://play.nativescript.org/?template=play-ng&id=zWAV8w&v=2)
above is playground demo link which can be used to reproduced the bug.
in above example when pullToRefresh initiated from both the tabs for around 10 to 20 times. then
call to `notifyPullToRefreshFinished()` doesn't work and RadListView remains in Refreshing states.
at least it seams from UI.

in above example if you run code inside `zone.runOutsideAngular` then this bug produces more frequently.
```
doRefresh(type, args) {
        let refresher = args.object;
        this.zone.runOutsideAngular(() => {
            // setTimeout(() => {
        this.http.get("https://reqres.in/api/users?per_page=12").toPromise().then((data) => {
            let d: any = data;
            d = d.data
            console.log(d)
            d=d.concat(d);
            d=d.concat(d);
            d=d.concat(d);
            d=d.concat(d);
            this.group.images = d;
            this.ref(refresher);
        })
                
            // }, 1000)    
         })
        
    }
```

in real project it happens every single time. when used 2 RadListView inside 2 tabs of TabView and setting same function as refreshCallback to both the RadListView. i'm unable to attach that project that is why i had created playground demo in which bug happens less frequently.

**Comment by bhavincb** [comment] 2018-05-11 16:45
hii @NickIliev ,
i had tested it on xiomi redmi 3s prime and samsung J7 max. issue can be reproduced by rapidly refreshing both ListView one after another. in some devices it may take very long to produce. but it is there. this issue was reported by through testing on both devices.

**Comment by NickIliev** [comment] 2018-06-21 12:48
@bhavincb possibly related to [this known issue](https://github.com/NativeScript/android-runtime/issues/404). As I am not able to reproduce on any device on my side I am currently closing this issue.

**Closed by NickIliev** 2018-06-21 12:48 UTC
Labels: listview, needs more info
