### ISSUE TITLE
Calender disabled days color is removed on styling

### ISSUE THREAD

**Issue by LeonBorlinghaus** [telerik/nativescript-ui-feedback#435] opened 2017-12-05 12:32 UTC
Hi,

when adding to the NativeScirpt Pro UI Calendar a maximum date

`this._calendar.calendar.maxDate = new Date();`

the dates are disabled in iOS and Android. They are now in a gray color.
As soon as I start styling the something on the calendar the disabled days are getting changed to a black color on IOS. They are still not clickable. On Android they are still in a gray color.

I'm styling like this:
```
 <RadCalendar
        locale="de-DE"
        #calendar
        [eventSource]="events"
        [monthViewStyle]="monthViewStyle"
        [monthNamesViewStyle]="monthNamesViewStyle"
        [yearViewStyle]="yearViewStyle"
        (dateSelected)="dateSelected($event)"></RadCalendar>
```

and then in a service im providing the data:

```
const monthViewStyle = new CalendarMonthViewStyle();
        monthViewStyle.backgroundColor = '#ffffff';
        monthViewStyle.showTitle = true;
        monthViewStyle.showWeekNumbers = false;
        monthViewStyle.showDayNames = true;
        monthViewStyle.selectionShape = isIOS ? 'Round' : 'None';
        monthViewStyle.selectionShapeSize = 15;
        monthViewStyle.selectionShapeColor = '#FF2D55';
```

Im using: 

> "tns-android": {
>       "version": "3.2.0"
>     },
>     "tns-ios": {
>       "version": "3.2.0"
>     },
> "nativescript-pro-ui": "^3.2.0",

Before styling something:
![bildschirmfoto 2017-12-05 um 13 28 44](https://user-images.githubusercontent.com/30794827/33607194-88353c00-d9c0-11e7-9ef6-5dc59f5acb81.png)

After styling:
![bildschirmfoto 2017-12-05 um 13 29 21](https://user-images.githubusercontent.com/30794827/33607193-88183272-d9c0-11e7-8805-669a4c1927dc.png)

Is there anyway to style the calendar on IOS and keep disabled days in that gray color?

**Comment by tsonevn** [comment] 2017-12-07 14:37
Hi @LeonBorlinghaus,
At this time there is no functionality, which provides support for styling the disabled days. I will log this as a new feature request.
For further info please keep track on the issue.

**Comment by YvesCandel** [comment] 2017-12-08 15:55
We would really like to see this feature implemented for iOS...

**Comment by cycchow** [comment] 2018-03-01 07:19
any way that i can modify the style of the disabled day?

**Comment by tgpetrov** [comment] 2018-07-10 13:55
This is a duplicate of the following issues:
1) For the issue that the styling for non-current month cells is reset, when another style is used, refer to [this issue](https://github.com/telerik/nativescript-ui-feedback/issues/568).
2) For the feature request to add a style that can be applied to non-current month cell, refer to [this issue](https://github.com/telerik/nativescript-ui-feedback/issues/576).

**Closed by tgpetrov** 2018-07-10 13:55 UTC
Labels: calendar, feature
