### ISSUE TITLE
Build Failure with exception

### ISSUE THREAD

**Issue by simranraza** [telerik/nativescript-ui-feedback#313] opened 2017-09-27 05:07 UTC
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':mergeF0F1F2DebugResources'.
> Error: Failed to crunch file C:\work\nativescript_projects\nativescript-ui-samples-angular\sdkAngular\platforms\android\build\intermediates\exploded-aar\com.android.support\appcompat-v7\26.0.0-alpha1\res\drawable-xxhdpi-v4\abc_textfield_search_activated_mtrl_alpha.9.png into C:\work\nativescript_projects\nativescript-ui-samples-angular\sdkAngular\platforms\android\build\intermediates\res\merged\F0F1F2\debug\drawable-xxhdpi-v4\abc_textfield_search_activated_mtrl_alpha.9.png

**Comment by VladimirAmiorkov** [comment] 2017-09-27 07:49
Hi @simranraza ,

Could you use our issue template and provide all of the required information and details. Without that information it is not possible to understand fully the issue that is being reported and how it can be reproduced. By providing those details you enable us to address your questions and/or issue report in a timely manner.

**Comment by Sharique-Hasan** [comment] 2017-09-27 23:00
I was also facing this issue. This was my package json:
tns --version: 3.0.3
```
  "name": "angular-seed-advanced",
  "version": "0.0.0",
  "nativescript": {
    "id": "com.yourdomain.nativescript",
    "tns-ios": {
      "version": "3.0.0"
    },
    "tns-android": {
      "version": "3.2.0"
    }
  },
  "scripts": {
    "preinstall": "mkdirp app",
    "clean": "rimraf platforms node_modules lib hooks app && mkdirp app",
    "ns-bundle": "ns-bundle",
    "start-android-bundle": "npm run ns-bundle --android --start-app",
    "start-ios-bundle": "npm run ns-bundle --ios --start-app",
    "build-android-bundle": "npm run ns-bundle --android --build-app",
    "build-ios-bundle": "npm run ns-bundle --ios --build-app"
  },
  "dependencies": {
    "@angular/animations": "~4.1.2",
    "@angular/common": "~4.1.2",
    "@angular/compiler": "~4.1.2",
    "@angular/core": "~4.1.2",
    "@angular/forms": "~4.1.2",
    "@angular/http": "~4.1.2",
    "@angular/platform-browser": "~4.1.2",
    "@angular/router": "~4.1.2",
    "@ngrx/core": "^1.2.0",
    "@ngrx/effects": "^2.0.3",
    "@ngrx/store": "^2.2.2",
    "@ngx-translate/core": "^6.0.1",
    "@ngx-translate/http-loader": "0.0.3",
    "angulartics2": "^2.2.1",
    "lodash": "^4.17.4",
    "moment": "^2.18.1",
    "nativescript-angular": "~3.0.0",
    "nativescript-autocomplete": "^1.0.0",
    "nativescript-checkbox": "^2.1.11",
    "nativescript-drop-down": "^3.1.2",
    "nativescript-localstorage": "^1.1.2",
    "nativescript-ngx-fonticon": "^2.2.3",
    "nativescript-pro-ui": "^3.1.3",
    "nativescript-svg": "^1.3.4",
    "nativescript-telerik-ui": "^3.1.3",
    "nativescript-theme-core": "^1.0.4",
    "ngrx-store-freeze": "0.1.9",
    "reflect-metadata": "^0.1.8",
    "rxjs": "^5.4.0",
    "tns-core-modules": "~3.0.0",
    "world-countries": "^1.8.1",
    "zone.js": "^0.8.10"
  },
  "devDependencies": {
    "@angular/compiler-cli": "~4.1.2",
    "@ngrx/store-devtools": "~3.2.4",
    "@ngtools/webpack": "1.3.1",
    "@types/jasmine": "2.5.41",
    "@types/lodash": "4.14.63",
    "babel-traverse": "6.11.4",
    "babel-types": "6.11.1",
    "babylon": "6.8.4",
    "codelyzer": "^3.0.1",
    "copy-webpack-plugin": "~4.0.1",
    "extract-text-webpack-plugin": "~2.1.0",
    "fs-extra": "^0.30.0",
    "glob": "^7.0.5",
    "lazy": "1.0.11",
    "nativescript-css-loader": "~0.26.0",
    "nativescript-dev-android-snapshot": "^0.0.9",
    "nativescript-dev-sass": "^1.1.1",
    "nativescript-dev-webpack": "^0.5.0",
    "opener": "^1.4.1",
    "raw-loader": "~0.5.1",
    "resolve-url-loader": "~2.0.2",
    "rimraf": "^2.5.3",
    "tar.gz": "^1.0.5",
    "tns-platform-declarations": "^3.0.1",
    "tslint": "^5.2.0",
    "typescript": "2.3.4",
    "webpack": "~2.5.1",
    "webpack-sources": "~0.2.3"
  }
}

**Comment by VladimirAmiorkov** [comment] 2017-09-28 07:10
Hi @Sharique-Hasan @simranraza ,

The reason for this issue is that you have both `nativescript-telerik-ui` and `nativescript-pro-ui` as `dependencies`. Because the nativescript-telerik-ui is deprecated and is replaced by the new free nativescript-pro-ui plugin both of who use the same native libraries it is not possible and not needed to have them both as dependencies. Simply:

1. Remove the `nativescript-telerik-ui` from `dependencies` (`tns plugin remove nativescript-telerik-ui`)
2. Delete the platform and node_modules folders inside your {N} application

**Comment by VladimirAmiorkov** [comment] 2017-09-28 07:11
Closing this issue for now. If you continue to experience this issue after the above step please let us know.

**Closed by VladimirAmiorkov** 2017-09-28 07:11 UTC

**Comment by Sharique-Hasan** [comment] 2017-09-28 15:44
@VladimirAmiorkov I am still seeing this issue. I have downloaded the sdkAngular app with this package json:

```
{
  "name": "nativescript-telerik-ui-sdk-angular-examples",
  "version": "3.0.0",
  "description": "Nativescript project that demonstrates the Progress NativeScript UI suite with Angular",
  "license": "SEE LICENSE IN <your-license-filename>",
  "readme": "NativeScript Application",
  "repository": {
    "type": "git",
    "url": "git@github.com/telerik/nativescript-ui-samples-angular.git"
  },
  "nativescript": {
    "id": "org.nativescript.sdkAngular",
    "tns-ios": {
      "version": "3.2.0"
    },
    "tns-android": {
      "version": "3.2.0"
    }
  },
  "dependencies": {
    "@angular/common": "4.3.2",
    "@angular/compiler": "4.3.2",
    "@angular/core": "4.3.2",
    "@angular/forms": "4.3.2",
    "@angular/http": "4.3.2",
    "@angular/platform-browser": "4.3.2",
    "@angular/platform-browser-dynamic": "4.3.2",
    "@angular/router": "4.3.2",
    "nativescript-angular": "4.2.0",
    "nativescript-fresco": "^3.0.2",
    "nativescript-intl": "^3.0.0",
    "nativescript-pro-ui": "3.1.3",
    "nativescript-unit-test-runner": "^0.3.2",
    "rxjs": "~5.3.0",
    "tns-core-modules": "3.2.0",
    "zone.js": "~0.8.2"
  },
  "devDependencies": {
    "@angular/compiler-cli": "^4.3.2",
    "@ngtools/webpack": "~1.5.3",
    "babel-traverse": "6.24.1",
    "babel-types": "6.24.1",
    "babylon": "6.17.0",
    "chai": "^3.5.0",
    "codelyzer": "^3.0.0",
    "copy-webpack-plugin": "~4.0.1",
    "extract-text-webpack-plugin": "~2.1.0",
    "filewalker": "0.1.3",
    "karma": "^1.6.0",
    "karma-chai": "^0.1.0",
    "karma-mocha": "^1.3.0",
    "karma-nativescript-launcher": "^0.4.0",
    "lazy": "1.0.11",
    "mocha": "^3.3.0",
    "nativescript-css-loader": "~0.26.0",
    "nativescript-dev-typescript": "~0.5.0",
    "nativescript-dev-webpack": "0.7.1",
    "raw-loader": "~0.5.1",
    "resolve-url-loader": "~2.0.2",
    "tns-platform-declarations": "3.2.0",
    "tslint": "^5.1.0",
    "typescript": "~2.3.2",
    "webpack": "~3.0.0",
    "webpack-bundle-analyzer": "^2.8.2",
    "webpack-sources": "~1.0.1"
  },
  "scripts": {
    "ns-bundle": "ns-bundle",
    "tslint": "tslint --project tsconfig.json --config tslint.json",
    "publish-ios-bundle": "npm run ns-bundle --ios --publish-app",
    "generate-android-snapshot": "generate-android-snapshot --targetArchs arm,arm64,ia32 --install",
    "start-android-bundle": "npm run ns-bundle --android --run-app",
    "start-ios-bundle": "npm run ns-bundle --ios --run-app",
    "build-android-bundle": "npm run ns-bundle --android --build-app",
    "build-ios-bundle": "npm run ns-bundle --ios --build-app"
  }
}
```
