### ISSUE TITLE
[Calendar] Erratic behaviour in selectedDateRange through dateSelected event

### ISSUE THREAD

**Issue by codeback** [telerik/nativescript-ui-feedback#212] opened 2017-06-15 11:01 UTC
I'm using RadCalendar in a NS + Angular app (Android). While this #211 is implemented, I'm getting the selected range as follows:

```
<StackLayout>
    <RadCalendar  #myCalendar selectionMode="Range" (dateSelected)="onDateSelected($event)"></RadCalendar>  
</StackLayout>
```

```
import { Component, ViewChild  } from "@angular/core";
import { RadCalendarComponent } from "nativescript-telerik-ui-pro/calendar/angular";
import { RadCalendar } from "nativescript-telerik-ui-pro/calendar";
@Component({
    moduleId: module.id,
    selector: "tk-calendar-getting-started",
    templateUrl: "calendar-getting-started.component.html"
})
export class CalendarGettingStartedComponent {
 
@ViewChild("myCalendar") _calendar: RadCalendarComponent;
    onDateSelected(args){
        console.log("date selected");
        console.log(args.date);
        console.log(this._calendar.calendar.selectedDateRange.startDate);
        console.log(this._calendar.calendar.selectedDateRange.endDate);
    }
   
}
```
The values of startDate and endDate are not always correct. Please see gif below:

![hoppin_calendar](https://user-images.githubusercontent.com/1965169/27178424-6daca5ae-51ca-11e7-9493-49f0e23c777b.gif)

**Comment by ginev** [comment] 2017-06-15 14:23
@codeback, this issue has been now addressed in our internal codebase and will be part of our next official release due to the end of June. You will be able to check the bits in an hour or so via the @next version of nativescript-telerik-ui-pro on npmjs.

**Comment by codeback** [comment] 2017-06-15 16:36
@ginev I purchased nativescript-telerik-ui-pro. Should I download the @next version from npm or it is available in my Telerik account. 

Thanks.

**Comment by ginev** [comment] 2017-06-16 07:30
@codeback - we are uploading the Trial version only - you can simply use it to check that the fix works correctly alongside our efforts to test it. If there's something that works not as expected, that will help us further investigate and provide a fix on time.

The official version is due to 2 weeks. Is that alright with you?

**Comment by codeback** [comment] 2017-06-16 07:44
@ginev this is a problem for us because we have a production ready release of our App that is just waiting for this to be solve. 

Is it possible to give me a link to this release in my Telerik account? There is a 'Internal Build' section that is good for this kind of 'intermediate versions', don't you think so?

**Comment by Natalia-Hristova** [comment] 2017-06-20 08:41
Hi @codeback ,

This issue is fixed and it will be available in our next official release(end of June). If you want to test it out before that you can use the "next" version of the nativescript-telerik-ui-pro plugin. Simply install that version of the plugin: ``` tns plugin add nativescript-telerik-ui-pro@next``` . 

**NOTE** that the next version is updated on daily/hourly basis from our current development brach which makes it not a good option for production applications but it is a great way to verify fixes and test new functionality.

**Closed by Natalia-Hristova** 2017-06-20 08:41 UTC
Labels: bug, calendar

**Comment by piotrilski** [comment] 2017-10-14 11:26
It seems that I'm able to reproduce something very similar with the latest version of nativescript-telerik-ui-pro (as of today it is 3.1.4). All details are here: https://github.com/telerik/nativescript-ui-feedback/issues/336
