### ISSUE TITLE
Error autocomplete

### ISSUE THREAD

**Issue by cmargulhano** [telerik/nativescript-ui-feedback#298] opened 2017-09-20 16:39 UTC
I did the example link: http://docs.telerik.com/devtools/nativescript-ui/Controls/Angular/AutoCompleteTextView/display-modes

I have the error below.
Someone can help?

```
            <RadAutoCompleteTextView #autocmp [items]="dataItems" suggestMode="Suggest" displayMode="Plain" completionMode="StartsWith">
                <SuggestionView tkAutoCompleteSuggestionView>
                    <ng-template tkSuggestionItemTemplate let-item="item">
                        <StackLayout orientation="vertical" padding="10">
                            <Label [text]="item.text"></Label>
                        </StackLayout>
                    </ng-template>
                </SuggestionView>
            </RadAutoCompleteTextView>
```

An uncaught Exception occurred on "main" thread.
com.tns.NativeScriptException: 
Calling js method onCreateViewHolder failed

Error: Expecting a valid View instance.
File: "file:///data/data/com.xxxxxx.enterprise.app/files/app/tns_modules/tns-core-modules/ui/core/view-base/view-base.js, line: 408, column: 12

StackTrace: 
    Frame: function:'ZoneAwareError', file:'file:///data/data/com.xxxxxx.enterprise.app/files/app/tns_modules/nativescript-angular/zone-js/dist/zone-nativescript.js', line: 993, column: 33
    Frame: function:'ViewBase._addView', file:'file:///data/data/com.xxxxxx.enterprise.app/files/app/tns_modules/tns-core-modules/ui/core/view-base/view-base.js', line: 408, column: 19
    Frame: function:'LayoutBaseCommon.addChild', file:'file:///data/data/com.xxxxxx.enterprise.app/files/app/tns_modules/tns-core-modules/ui/layouts/layout-base-common.js', line: 44, column: 14
    Frame: function:'AutoCompleteAdapter.onCreateViewHolder', file:'file:///data/data/com.xxxxxx.enterprise.app/files/app/tns_modules/nativescript-pro-ui/autocomplete/autocomplete.js', line: 69, column: 24

    at com.tns.Runtime.callJSMethodNative(Native Method)
    at com.tns.Runtime.dispatchCallJSMethodNative(Runtime.java:1084)
    at com.tns.Runtime.callJSMethodImpl(Runtime.java:966)
    at com.tns.Runtime.callJSMethod(Runtime.java:953)
    at com.tns.Runtime.callJSMethod(Runtime.java:937)
    at com.tns.Runtime.callJSMethod(Runtime.java:929)
    at com.tns.gen.com.telerik.widget.autocomplete.AutoCompleteAdapter_frnal_ts_helpers_l58_c38__AutoCompleteAdapter.onCreateViewHolder(com.telerik.widget.autocomplete.AutoCompleteAdapter.java)
    at com.telerik.widget.list.ListViewWrapperAdapter.onCreateViewHolder(ListViewWrapperAdapter.java:459)
    at com.telerik.widget.list.ListViewWrapperAdapter.onCreateViewHolder(ListViewWrapperAdapter.java:20)
    at android.support.v7.widget.RecyclerView$Adapter.createViewHolder(RecyclerView.java:6411)
    at android.support.v7.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:5597)
    at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5482)
    at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5478)
    at android.support.v7.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:2215)
    at android.support.v7.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:1542)
    at android.support.v7.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1502)
    at android.support.v7.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:595)
    at android.support.v7.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:3625)
    at android.support.v7.widget.RecyclerView.dispatchLayout(RecyclerView.java:3354)
    at android.support.v7.widget.RecyclerView.onLayout(RecyclerView.java:3886)
    at com.telerik.widget.list.RadListView.onLayout(RadListView.java:596)
    at android.view.View.layout(View.java:17538)
    at android.view.ViewGroup.layout(ViewGroup.java:5616)
    at android.widget.RelativeLayout.onLayout(RelativeLayout.java:1079)
    at android.view.View.layout(View.java:17538)
    at android.view.ViewGroup.layout(ViewGroup.java:5616)
    at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
    at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
    at android.view.View.layout(View.java:17538)
    at android.view.ViewGroup.layout(ViewGroup.java:5616)
    at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
    at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
    at android.view.View.layout(View.java:17538)
    at android.view.ViewGroup.layout(ViewGroup.java:5616)
    at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:2354)
    at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2081)
    at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1258)
    at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6348)
    at android.view.Choreographer$CallbackRecord.run(Choreographer.java:871)
    at android.view.Choreographer.doCallbacks(Choreographer.java:683)
    at android.view.Choreographer.doFrame(Choreographer.java:619)
    at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:857)
    at android.os.Handler.handleCallback(Handler.java:751)
    at android.os.Handler.dispatchMessage(Handler.java:95)
    at android.os.Looper.loop(Looper.java:154)
    at android.app.ActivityThread.main(ActivityThread.java:6123)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:867)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:757)

**Comment by VladimirAmiorkov** [comment] 2017-09-20 18:09
Hi @cmargulhano ,

Could you please provide all of the necessary information that was requested when you started this thread, including the versions of of both the used nativescript-telerik-ui-pro, tns-core-modules and nativescript-angular.

Note that the pre populated issue template is a requirement of this github repository in order to streamline the process of reporting and resolving issues, deleting that and providing halfway details only extends the time for the issue being validated and resolved. Thank you.

**Comment by cmargulhano** [comment] 2017-09-20 18:17
"nativescript-pro-ui": "3.1.2"
"tns-android": "3.2.0"
"tns-ios": "3.2.0"
"nativescript-angular": "4.2.0",

$ tns --version
 3.1.3

**Comment by VladimirAmiorkov** [comment] 2017-09-21 06:58
Hi @cmargulhano ,

I am not able to reproduce the described error when running our sdkAngular examples (found [here](https://github.com/telerik/nativescript-ui-samples)) from which the code snippet is taken from.

Can you try to run those examples and see if the same issue is still observed. It is worth mentioning that you it is recommended to update to the current latest tns version 3.2.1 (`npm install -g nativescript`) as it includes some bug fixes concerning build failures.

**Comment by dbeulen** [comment] 2017-10-13 15:03
Did you find any fix for this? I'm having the exact same issue.

tns version: 3.2.1
nativescript-pro-ui: 3.1.4

**Comment by nmongiya** [comment] 2017-10-16 06:50
I am also facing the an exception when you try to tap back button from keypad but it is intermittent. Can not reproduce this every time. https://github.com/telerik/nativescript-ui-feedback/issues/330

**Comment by tsonevn** [comment] 2017-12-06 13:45
Tested this case with https://github.com/telerik/nativescript-ui-samples-angular/tree/release/sdkAngular/app/autocomplete/getting-started  and was unable to recreate this problem. I am closing this issue, I will reopen it when you provide sample project, which could be used for debugging.
Regards,
@tsonevn

**Comment by nmongiya** [comment] 2018-01-15 05:59
@tsonevn 
[2018-01-15 at 15-49-27.zip](https://github.com/telerik/nativescript-ui-feedback/files/1630525/2018-01-15.at.15-49-27.zip)
 I have cloned the sample project from https://github.com/telerik/nativescript-ui-samples-angular
Just added few more data points in the sample as the following
` for (var j = 0; j < 50; j++) {
            for (var i = 0; i < this.countries.length; i++) {
                if(i >0)
                {        this._items.push(new TokenModel(this.countries[ i ] + ' ' +this.countries[ i-1 ] + ' ' + +this.countries[ i-1 ], undefined));
                }else
                {   this._items.push(new TokenModel(this.countries[ i ] + i, undefined));  } }  }
        `
I am using completionmode as contains and displaymode Plain
and followed the same step as I mentioned above 
" just search for few names and press back button multiple times. I am successfully able to reproduce the error.

`An uncaught Exception occurred on "main" thread.
com.tns.NativeScriptException: 
Calling js method onBindViewHolder failed

TypeError: Cannot set property 'bindingContext' of undefined
File: "file:///data/data/org.nativescript.sdkAngular/files/app/tns_modules/nativescript-pro-ui/autocomplete/autocomplete.js, line: 83, column: 41

StackTrace: 
	Frame: function:'AutoCompleteAdapter.onBindViewHolder', file:'file:///data/data/org.nativescript.sdkAngular/files/app/tns_modules/nativescript-pro-ui/autocomplete/autocomplete.js', line: 83, column: 42


	at com.tns.Runtime.callJSMethodNative(Native Method)
	at com.tns.Runtime.dispatchCallJSMethodNative(Runtime.java:1088)
	at com.tns.Runtime.callJSMethodImpl(Runtime.java:970)
	at com.tns.Runtime.callJSMethod(Runtime.java:957)
	at com.tns.Runtime.callJSMethod(Runtime.java:941)
	at com.tns.Runtime.callJSMethod(Runtime.java:933)
	at com.tns.gen.com.telerik.widget.autocomplete.AutoCompleteAdapter_frnal_ts_helpers_l58_c38__AutoCompleteAdapter.onBindViewHolder(Unknown Source:27)
	at com.telerik.widget.list.ListViewWrapperAdapter.onBindViewHolder(ListViewWrapperAdapter.java:247)
	at com.telerik.widget.list.ListViewWrapperAdapter.onBindViewHolder(ListViewWrapperAdapter.java:20)
	at android.support.v7.widget.RecyclerView$Adapter.onBindViewHolder(RecyclerView.java:6400)
	at android.support.v7.widget.RecyclerView$Adapter.bindViewHolder(RecyclerView.java:6433)
	at android.support.v7.widget.RecyclerView$Recycler.tryBindViewHolderByDeadline(RecyclerView.java:5377)
	at android.support.v7.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:5640)
	at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5482)
	at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5478)
	at android.support.v7.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:2215)
	at android.support.v7.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:1542)
	at android.support.v7.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1502)
	at android.support.v7.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:595)
	at android.support.v7.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:3625)
	at android.support.v7.widget.RecyclerView.dispatchLayout(RecyclerView.java:3354)
	at android.support.v7.widget.RecyclerView.onLayout(RecyclerView.java:3886)
	at com.telerik.widget.list.RadListView.onLayout(RadListView.java:596)
	at android.view.View.layout(View.java:19590)
	at android.view.ViewGroup.layout(ViewGroup.java:6053)
	at android.widget.RelativeLayout.onLayout(RelativeLayout.java:1080)
	at android.view.View.layout(View.java:19590)
	at android.view.ViewGroup.layout(ViewGroup.java:6053)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
	at android.view.View.layout(View.java:19590)
	at android.view.ViewGroup.layout(ViewGroup.java:6053)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
	at android.view.View.layout(View.java:19590)
	at android.view.ViewGroup.layout(ViewGroup.java:6053)
	at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:2484)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2200)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1386)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6733)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:911)
	at android.view.Choreographer.doCallbacks(Choreographer.java:723)
	at android.view.Choreographer.doFrame(Choreographer.java:658)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:897)
	at android.os.Handler.handleCallback(Handler.java:789)
	at android.os.Handler.dispatchMessage(Handler.java:98)
	at android.os.Looper.loop(Looper.java:164)
	at android.app.ActivityThread.main(ActivityThread.java:6541)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)
`

[2018-01-15 at 15-49-27.zip](https://github.com/telerik/nativescript-ui-feedback/files/1630519/2018-01-15.at.15-49-27.zip)

**Comment by tsonevn** [comment] 2018-01-15 15:51
Hi @nmongiya,
I reviewed your video and tested this case again.
After I made the suggested changes I was able to recreate this behavior while using [nativescript-ui-samples-angular](https://github.com/telerik/nativescript-ui-samples-angular) project.
I was able to recreate this problem only on Android.
For further info, please keep track on the issue.

**Comment by nmongiya** [comment] 2018-01-25 02:15
Hi @tsonevn , Did you manage to look into this? it was suggested in #419 that following change may prevent app crash. Do you favour this?
```
configurations.all {
    resolutionStrategy.eachDependency { DependencyResolveDetails details ->
        def requested = details.requested
        if (requested.group == "com.android.support") {
            if (!requested.name.startsWith("multidex")) {
                details.useVersion "25.3.0"
            }
        }
    }
}
```

**Comment by tsonevn** [comment] 2018-01-25 09:43
Hi @nmongiya, 
Thank you for the suggestion, 
I review the other issue, however in opinion the both issues are not related to each other, 
The suggested solution does not seem to be a valid fix for this case, while the problem is related to the binding context.

**Comment by nmongiya** [comment] 2018-01-28 23:14
@tsonevn 
I have tried to check the 'undefined' and it seems that app is not crashing anymore.
`AutoCompleteAdapter.prototype.onBindViewHolder = function (holder, position) {
            var nativeItem = this.getFilteredList().get(position);
            var img = nativeItem.getNsImageName();
            var model = new TokenModel(nativeItem.getText(), img);
            **if (holder.nsView != undefined) {**
                holder.nsView.bindingContext = model;
            **}**
            
            var args = {
                eventName: commonModule.RadAutoCompleteTextView.itemLoadingEvent,
                index: position,
                view: holder['nsView']._subViews[0],
                android: holder,
                data: model
            };
            this.owner.notify(args);
        };`

**Closed** 2018-03-07 12:34 UTC
Labels: autocomplete, backlog, bug, os: android, ready for release, severity: high
