### ISSUE TITLE
[RadSideDrawer] [ios] iPhoneX ActionBar sizing problem in landscape

### ISSUE THREAD

**Issue by PeterStaev** [telerik/nativescript-ui-feedback#695] opened 2018-06-07 20:09 UTC
> Please take a minute to read our [NativeScript Code of Conduct](https://github.com/NativeScript/codeofconduct) before proceeding with posting issues or discussing. The purpose of this guide is to make communication and cooperation within our forums a pleasure for you and the other members.

### Did you verify this is a real problem by searching the [NativeScript Forum](https://discourse.nativescript.org/)?
Yes

### Tell us about the problem
On iPhoneX when the phone is in landscape and you have drawer as the `app-root` the `ActionBar` is not sized correctly and has nasty whitespaces on both left/right sides. If the drawer is removed the problem is not present and the `ActionBar` takes the full width of the screen. 

### Which platform(s) does your issue occur on?
iOS (iPhoneX)

### Please provide the following version numbers that your issue occurs with:
- **Progress NativeScript UI version:** 4.1.1
- **CLI:** 4.1
- **Cross-platform modules:** 4.1
- **Runtime(s):** 4.1

### Please tell us how to recreate the issue in as much detail as possible.
1. Playground: https://play.nativescript.org/?template=play-tsc&id=UGSylY
2. Rotate phone in landscape

**Comment by davorpeic** [comment] 2018-06-07 20:28
Hi Peter, not sure if related? https://github.com/NativeScript/NativeScript/issues/5672

**Comment by davorpeic** [comment] 2018-06-07 20:48
hmm, ok, was looking that issue few minutes back and it seems similar.

**Comment by tsonevn** [comment] 2018-06-12 08:17
The  issue seems to be duplicate of [#5782](https://github.com/NativeScript/NativeScript/issues/5782)

**Closed by tsonevn** 2018-06-12 08:17 UTC
