### ISSUE TITLE
RadListView scrollOffset jumps over large chunks of numbers at header elements

### ISSUE THREAD

**Issue by mimi1694** [telerik/nativescript-ui-feedback#656] opened 2018-05-08 20:58 UTC
> Please take a minute to read our [NativeScript Code of Conduct](https://github.com/NativeScript/codeofconduct) before proceeding with posting issues or discussing. The purpose of this guide is to make communication and cooperation within our forums a pleasure for you and the other members.

### Did you verify this is a real problem by searching the [NativeScript Forum](https://discourse.nativescript.org/)?
xYes/No_

### Tell us about the problem
_Please, ensure your title is less than 63 characters long and starts with a capital
letter._
RadListView getScrollOffset jumps over large chunks of numbers at header elements
I have a RadListView in which some elements are smaller than others to act as a type of header. I need to implement a type of sticky header functionality, and need to grab the current scrollOffset during the radListView.onScroll event. However, when the smaller header elements reach the top, the scrollOffset seems to jump up at least 20px, increasing in the amount jumped each time. Also, the offset will occasionally "jump" backwards.  This does not happen on ios.

### Which platform(s) does your issue occur on?
_Android (if applicable tell us the specific version of the platform)_

### Please provide the following version numbers that your issue occurs with:
3.3.5 **Progress NativeScript UI version:** (the version of nativescript-telerik-ui/-pro in the `package.json`)
4.0.0 **CLI:** (run `tns --version` to fetch it)
~4.0.0 **Cross-platform modules:** (the version of tns-core-modules in the `package.json`)
4.0.1 **Runtime(s):** (the `"tns-android"` and `"tns-ios"` properties in the `package.json`)

### Please tell us how to recreate the issue in as much detail as possible.
1. clone the repo from https://github.com/mimi1694/TestListApp.git
3. cd TestListApp
3. tns run android
4. When scrolling, look at the console.logs. When headers reach the top you should see a large jump in the numbers.

### Is there code involved? If so, please share the minimal amount of code needed to recreate the problem.
_(You can paste entire code snippets or attach a runnable project)_

This code was modified from the Telerik basic Angular template app, and can also be found here: https://github.com/mimi1694/TestListApp 

items.component.html:
```
<ActionBar title="My App" class="action-bar">
</ActionBar>

<GridLayout class="page" columns="*" rows="*" scrollEnabled="false">
    
    <RadListView class="list-group" [items]="items" [itemTemplateSelector]="templateSelector" (scrolled)="onScroll($event)" col="0" row="0">
      <ListViewLinearLayout  scrollDirection="Vertical" itemInsertAnimation="Default" itemDeleteAnimation="Default">

        <ng-template tkListItemTemplate tkTemplateKey="header" let-item="item">
            <GridLayout class="list-group-item header" backgroundColor="Gray" height="22" columns="*" rows="*">
                <Label class="list-group-item-heading" isUserInteractionEnabled="false" col="0" row="0"></Label>
            </GridLayout>
        </ng-template>

        <ng-template tkListItemTemplate tkTemplateKey="item" let-item="item">
            <GridLayout class="list-group-item"  columns="*" rows="*">
              <Label class="list-group-item-heading" [nsRouterLink]="['/item', item.id]" [text]="item.name" col="0" row="0"></Label>
            </GridLayout>
        </ng-template>

      </ListViewLinearLayout>
    </RadListView>

  </GridLayout>
```

items.component.ts:
```
import { Component, OnInit, Input } from "@angular/core";

import { Item } from "./item";
import { ItemService } from "./item.service";
import { ListViewScrollEventData } from "nativescript-ui-listview";

@Component({
    selector: "ns-items",
    moduleId: module.id,
    templateUrl: "./items.component.html",
})
export class ItemsComponent implements OnInit {
    @Input() items: Item[];
    @Input() banner: [""];

    constructor(private itemService: ItemService) { }

    ngOnInit(): void {
        this.items = this.itemService.getItems();
    }
    templateSelector(item: any, index: number, items: any): string {
        if (item.role === "header") return "header";
        else return "item";
    }
    onScroll(args: ListViewScrollEventData): void {
       console.log("onScroll args.scrollOffset:", args.scrollOffset);
    }
}
```

item.service.ts:
```
import { Injectable } from "@angular/core";

import { Item } from "./item";

@Injectable()
export class ItemService {
    private items = new Array<Item>(
        { id: 0, name: "Defenders", role: "header" },
        { id: 19, name: "Digne", role: "Defender" },
        { id: 18, name: "Jordi Alba", role: "Defender" },
        { id: 14, name: "Mascherano", role: "Defender" },
        { id: 24, name: "Mathieu", role: "Defender" },
        { id: 23, name: "Umtiti", role: "Defender" },
        { id: 3, name: "Piqué", role: "Defender" },
        { id: 0, name: "Forwards", role: "header" },
        { id: 10, name: "Messi", role: "Forward" },
        { id: 11, name: "Neymar", role: "Forward" },
        { id: 17, name: "Paco Alcácer", role: "Forward" },
        { id: 9, name: "Suárez", role: "Forward" },
        { id: 0, name: "Goalkeepers", role: "header" },
        { id: 13, name: "Cillessen", role: "Goalkeeper" },
        { id: 25, name: "Masip", role: "Goalkeeper" },
        { id: 1, name: "Ter Stegen", role: "Goalkeeper" },
        { id: 0, name: "Midfielders", role: "header" },
        { id: 8, name: "A. Iniesta", role: "Midfielder" },
        { id: 22, name: "Aleix Vidal", role: "Midfielder" },
        { id: 21, name: "André Gomes", role: "Midfielder" },
        { id: 7, name: "Arda", role: "Midfielder" },
        { id: 6, name: "Denis Suárez", role: "Midfielder" },
        { id: 4, name: "I. Rakitic", role: "Midfielder" },
        { id: 12, name: "Rafinha", role: "Midfielder" },
        { id: 20, name: "Sergi Roberto", role: "Midfielder" },
        { id: 5, name: "Sergio", role: "Midfielder" },
    );

    getItems(): Item[] {
        return this.items;
    }

    getItem(id: number): Item {
        return this.items.filter(item => item.id === id)[0];
    }
}
```

**Comment by tgpetrov** [comment] 2019-02-27 11:34
Hi @mimi1694,
The issue is resolved with [nativescript-ui-listview@5.2.0](https://github.com/telerik/nativescript-ui-feedback/blob/master/releases/listview.md#v520-2019-february-25).

**Closed by tgpetrov** 2019-02-27 11:34 UTC
