### ISSUE TITLE
ScrollView memory leak

### ISSUE THREAD

**Issue by facetious** [telerik/nativescript-ui-feedback#847] opened 2018-09-24 15:16 UTC
### Did you verify this is a real problem by searching the [NativeScript Forum](https://discourse.nativescript.org/)?
Yes

### Tell us about the problem
I have detected a memory leak in the `ScrollView`'s `(scroll)` handler (at least on iOS).

### Which platform(s) does your issue occur on?
iOS. I have not tested Android, but it may be present there, as well.

### Please provide the following version numbers that your issue occurs with:
- **Progress NativeScript UI version:** 4.3.0-2018-09-19-01
- **CLI:** 4.3.0-2018-09-18-12265
- **Cross-platform modules:** ^4.3.0-2018-09-18-05
- **Runtime(s):** ^4.3.0-2018-09-19-01

### Please tell us how to recreate the issue in as much detail as possible.
1. Start the application
2. Swipe up and down while watching the memory chart
*** Note memory increases steadily and does not get freed.

3. Switch to 'ScrollView without (scroll)' and swipe up and down
*** Note that memory does not increase.

4. Switch to 'RadListView' and swipe up and down
*** Note that memory again increases steadily with swiping.

As an added bonus, switching between a `ScrollView` and the `RadListView` exhibits this issue of continually growing memory usage as the `RadListView` goes on and off screen: https://github.com/telerik/nativescript-ui-feedback/issues/825

### Is there code involved? If so, please share the minimal amount of code needed to recreate the problem.

    import { Component } from "@angular/core";

    @Component({
        selector: "gr-list",
        template: `<StackLayout>
            <Button (tap)="setType(1)" text="ScrollView with (scroll)"></Button>
            <Button (tap)="setType(2)" text="ScrollView without (scroll)"></Button>
            <Button (tap)="setType(3)" text="RadListView"></Button>

            <ScrollView *ngIf="type == 1" (scroll)="onScroll()">
                <StackLayout height="3000">
                    <Label *ngFor="let num of testData" [text]="'ScrollView with (scroll) ' + num"></Label>
                </StackLayout>
            </ScrollView>

            <ScrollView *ngIf="type == 2">
                <StackLayout height="3000">
                    <Label *ngFor="let num of testData" [text]="'ScrollView without (scroll) ' + num"></Label>
                </StackLayout>
            </ScrollView>

            <RadListView height="100%" *ngIf="type == 3" [items]="testData">
                <ng-template let-num="item">
                    <StackLayout>
                        <Label [text]="'RadListView ' + num"></Label>
                    </StackLayout>
                </ng-template>
            </RadListView>
        </StackLayout>`
    })
    export class ListComponent {
        testData: Array<number> = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20];
        type: number = 1;

        onScroll() {}

        setType(type: number) {
            this.type = type;
        }
    }

**Comment by facetious** [comment] 2018-09-28 21:06
I attempted to avoid this bug by implementing `ngAfterViewChecked()` (I have a 100Hz updating field on screen) which exhibits the bug as well. My suspicion is that there is some event tracking going on here that is storing all events for forensics reasons. It would be nice to be able to turn that off or have a cache limit on it or something.

**Comment by facetious** [comment] 2018-10-24 15:48
This needs to be promoted. It affects much more than just the `ScrollView`. This is a fundamental issue. Here is a Playground: https://play.nativescript.org/?template=play-ng&id=3hAqiz

This bug is exhibited when I download this and apply this diff to my `package.json`:

	9c9
	<             "version": "5.0.0-2018-10-17-175756-01"
	---
	>             "version": "4.2.0"
	12c12,15
	<             "version": "5.0.0-rc-2018-10-17-161243-01"
	---
	>             "version": "4.2.0"
	>         },
	>         "playground": {
	>             "id": "727444034.1527016119"
	46c49
	<         "tns-core-modules": "^5.2.0-2018-10-18-135500-02",
	---
	>         "tns-core-modules": "4.2.1",

# Unmodified memory profile
<img width="407" alt="unmodified" src="https://user-images.githubusercontent.com/1058563/47443485-65e49680-d782-11e8-8183-0f6c00b4987c.png">

# Diff applied memory profile
<img width="428" alt="diff-applied" src="https://user-images.githubusercontent.com/1058563/47443484-65e49680-d782-11e8-811f-161205de3e95.png">

**Comment by rafarx** [comment] 2018-10-30 16:34
I can confirm the exact same problem on android.

**Comment by rafarx** [comment] 2018-10-30 21:34
Setting scrollBarIndicatorVisible="false" in the scrollview seems to fix it.

**Comment by gogoout** [comment] 2018-11-03 06:50
I did a little testing based on the project NickIliev provided. So I updated `tns-core-modules` to the latest version which is `^5.2.0-2018-10-18-135500-02`(this version have the fix for https://github.com/telerik/nativescript-ui-feedback/issues/825) . And the bug can't reproduce on the version `tns-ios 4.3.0-2018-08-17-02` and can be reproduce on the version `4.3.0-2018-08-20-04`.

Below is the screenshot. It is worth metion because of the fix of https://github.com/telerik/nativescript-ui-feedback/issues/825 , the curve is a lot more gentle now but you can still notice that there is a leak.

### "4.3.0-2018-08-20-04"
![screen shot 2018-11-03 at 19 40 52](https://user-images.githubusercontent.com/7570175/47949004-82fa4000-dfa0-11e8-9c8e-d8f5dea9dfc1.png)


###  "4.3.0-2018-08-17-02"
<img width="528" alt="screen shot 2018-11-03 at 19 50 04" src="https://user-images.githubusercontent.com/7570175/47949064-ab366e80-dfa1-11e8-81a7-67aac774bd2e.png">

**Comment by gogoout** [comment] 2018-11-28 05:45
@VladimirAmiorkov any update on this issue? Any pull request that we can track? Appreciate in advance.

**Comment by VladimirAmiorkov** [comment] 2018-11-28 09:11
Hi @gogoout ,

The memory issues related to RadListView has been resolved and released in the latest versions of nativescript-ui-listview.

I have taken a look at the provided [playground demo](https://play.nativescript.org/?template=play-ng&id=3hAqiz) but have not see any list component inside. Are the above profiled screenshots from that demo or a different one because this issue is logged for ScrollViews and that demo does not use any.

**Comment by gogoout** [comment] 2018-11-28 09:56
Hi @VladimirAmiorkov ,
The screenshots is for this [demo](
https://github.com/NickIliev/NS-Issues-2018-II/tree/master/nativescript-ui-feedback/issue-847)

**Comment by gogoout** [comment] 2018-11-29 03:02
I've test the demo project with latest `RadListView(v5.0.0)`  `tns-ios v5.0.0` `tns-core-modules v5.0.5` . Seems the leak is still there.

![screen shot 2018-11-29 at 15 52 51](https://user-images.githubusercontent.com/7570175/49196421-c4d7a400-f3ef-11e8-87fb-34222998efb2.png)

**Comment by DimitarTodorov** [comment] 2018-12-18 15:09
Hi, @gogoout 
We tested with the latest released version of `tns-android` and `tns-ios` and we confirm that the issue is fixed. I'm closing this issue since it is now resolved.

**Closed by DimitarTodorov** 2018-12-18 15:09 UTC
Labels: backlog, bug, listview, os: ios, severity: high
