### ISSUE TITLE
com.telerik.android.primitives.widget.sidedrawer.RadSideDrawer is not a constructor In nativescript-ui-sidedrawer

### ISSUE THREAD

**Issue by AsrarMemon** [telerik/nativescript-ui-feedback#586] opened 2018-03-26 15:05 UTC
When i add nativescript-ui-sidedrawer 
and got error which i mention below 
```
System.err: com.tns.NativeScriptException: 
System.err: Calling js method onCreateView failed
System.err: 
System.err: TypeError: com.telerik.android.primitives.widget.sidedrawer.RadSideDrawer is not a constructor
System.err: File: "file:///data/data/org.nativescript.DynamicAccessOTP/files/app/tns_modules/nativescript-ui-sidedrawer/ui-sidedrawer.js, line: 103, column: 24
System.err: 
System.err: StackTrace: 
System.err: 	Frame: function:'RadSideDrawer.initDrawer', ...........

```

sample code 

```
<RadSideDrawer tkExampleTitle tkToggleNavButton>
        <StackLayout tkDrawerContent class="sideStackLayout">
            <StackLayout class="sideTitleStackLayout">
                <Label text="Navigation Menu"></Label>
            </StackLayout>
            <StackLayout class="sideStackLayout">
                <Label text="Primary" class="sideLabel sideLightGrayLabel"></Label>
                <Label text="Social" class="sideLabel"></Label>
                <Label text="Promotions" class="sideLabel"></Label>
                <Label text="Labels" class="sideLabel sideLightGrayLabel"></Label>
                <Label text="Important" class="sideLabel"></Label>
                <Label text="Starred" class="sideLabel"></Label>
                <Label text="Sent Mail" class="sideLabel"></Label>
                <Label text="Drafts" class="sideLabel"></Label>
            </StackLayout>
            <Label text="Close Drawer" color="lightgray" padding="10" style="horizontal-align: center" (tap)="onCloseDrawerTap()"></Label>
        </StackLayout>
        <StackLayout tkMainContent>
            <Label [text]="mainContentText" textWrap="true" class="drawerContentText"></Label>
            <Button text="OPEN DRAWER" (tap)="openDrawer()" class="drawerContentButton"></Button>
        </StackLayout>
    </RadSideDrawer>
```

and in .ts

```
import { Observable } from "tns-core-modules/data/observable";
import frame = require("tns-core-modules/ui/frame");
import { RadSideDrawer } from "nativescript-ui-sidedrawer";

export class GettingStartedViewModel extends Observable {
    constructor() {
        super();
        this.set("mainContentText", "SideDrawer for NativeScript can be easily setup in the XML definition of your page by defining main- and drawer-content. The component"
            + " has a default transition and position and also exposes notifications related to changes in its state. Swipe from left to open side drawer.");
    }

    public onOpenDrawerTap() {
        let sideDrawer: RadSideDrawer = <RadSideDrawer>( frame.topmost().getViewById("sideDrawer"));
        sideDrawer.showDrawer();
    }

    public onCloseDrawerTap() {
        let sideDrawer: RadSideDrawer = <RadSideDrawer>( frame.topmost().getViewById("sideDrawer"));
        sideDrawer.closeDrawer();
    }
}
```

can you please help me out how can i solve this issue ?

**Comment by alexcoroza** [comment] 2018-04-04 15:49
Why did you closed this issue? Did you find any solution? I'm experiencing this error and I dont know how to fix it. I just followed their documentation

**Comment by benjaminhorner** [comment] 2018-04-12 11:14
Same here with a blank new project and following the documentation example (Angular).

**Comment by NickIliev** [comment] 2018-04-12 14:04
Hey @AsrarMemon  @benjaminhorner  @alexcoroza can you guys share some more detailed information as requested in the "new issue" template

> ### Which platform(s) does your issue occur on?
> _iOS/Android/Both (if applicable tell us the specific version of the platform)_
> 
> ### Please provide the following version numbers that your issue occurs with:
> - **Progress NativeScript UI version:** (e.g. the version of nativescript-ui-sidedrawer in the `package.json`)
> - **CLI:** (run `tns --version` to fetch it)
> - **Cross-platform modules:** (the version of tns-core-modules in the `package.json`)
> - **Runtime(s):** (the `"tns-android"` and `"tns-ios"` properties in the `package.json`)
> 
> ### Please tell us how to recreate the issue in as much detail as possible.
> 1. Start the application ..
> 2. ...
>

**Comment by benjaminhorner** [comment] 2018-04-12 14:06
@NickIliev : yes. I am building a test project to illustrate the issue. What is the best way to share it with you guys?

**Comment by NickIliev** [comment] 2018-04-13 05:39
@AsrarMemon thanks for the reported issue. I think the issue is [related to this comment](https://github.com/telerik/nativescript-ui-feedback/issues/430#issuecomment-375654698).

I've created [this test project ](https://github.com/NickIliev/NS-Issues-2018/tree/master/nativescript-ui-feedback/issue_586) and indeed was able to reproduce the issue.
However, removing the platform folder and rebuild the application again has resolved the issue on my side.

**Comment by benjaminhorner** [comment] 2018-04-13 09:30
@NickIliev : It seems the two issues are related indeed. However, I did have to uninstall and reinstall multiple times the platforms in order to get this to work as expected.

**Comment by NickIliev** [comment] 2018-04-13 10:38
@benjaminhorner you can contact me in the community slack (username: niliev) to investigate the issue with the blank page-router-outlet content. I suspect it is related to a routing issue or layout structure and is not related to this one.

**Comment by DimitarTachev** [comment] 2018-05-11 13:28
Most probably related to https://github.com/NativeScript/nativescript-cli/issues/3354.

**Comment by nsplugins** [comment] 2018-05-25 12:47
Please use the provided workaround (remove platforms directory) for now. The progress of the issue can be checked in the related one in the NativeScript CLI repository.

**Closed by nsplugins** 2018-05-25 12:47 UTC
Labels: angular, bug, sidedrawer

**Comment by bracco23** [comment] 2018-10-02 18:14
@benjaminhorner @NickIliev I had this same issue and solved with the given workaround, but I am no facing the blank page problem. What is the reason for that? How can I fix it? Thank you.

**Comment by benjaminhorner** [comment] 2018-10-02 18:19
@bracco23 have you any code to share? Without any code it will be hard to help you.

**Comment by bracco23** [comment] 2018-10-03 17:48
Just an update, it must be something related to my configuration because the same code on a playground session (here: https://play.nativescript.org/?template=play-ng&id=HT6NVH) is working fine on the same phone. 

Now I tried cleaning everything and starting as clean as possible, so I did:
    rm -rf node_modules
    npm install
    npm update
    tns platform remove android
    tns platform add android
    tns run android

but the result was still buggy. I also noticed that in my version the SideDrawer doesn't actually cover the ActionBar, as it should according to the documentation of the new version.

For more info, this is my package.json

```
{
	"description": "NativeScript Application",
	"license": "SEE LICENSE IN <your-license-filename>",
	"readme": "NativeScript Application",
	"repository": "<fill-your-repository-here>",
	"nativescript": {
		"id": "org.nativescript.TrackingCalendar",
		"tns-android": {
			"version": "4.2.0"
		}
	},
	"dependencies": {
		"@angular/animations": "~5.2.0",
		"@angular/common": "~5.2.0",
		"@angular/compiler": "~5.2.0",
		"@angular/core": "~5.2.0",
		"@angular/forms": "~5.2.0",
		"@angular/http": "~5.2.0",
		"@angular/platform-browser": "~5.2.0",
		"@angular/platform-browser-dynamic": "~5.2.0",
		"@angular/router": "~5.2.0",
		"nativescript-angular": "~5.2.0",
		"nativescript-theme-core": "~1.0.4",
		"nativescript-ui-calendar": "^3.9.0",
		"nativescript-ui-sidedrawer": "^4.3.0",
		"reflect-metadata": "~0.1.8",
		"rxjs": "~5.5.2",
		"tns-core-modules": "^4.2.1",
		"zone.js": "~0.8.2"
	},
	"devDependencies": {
		"babel-traverse": "^6.26.0",
		"babel-types": "^6.26.0",
		"babylon": "6.4.5",
		"lazy": "1.0.11",
		"nativescript-dev-typescript": "~0.6.0",
		"typescript": "~2.6.2"
	}
}
```

**Comment by mhlulani** [comment] 2018-11-26 20:56
I was able to resolve the issue just by updating the the platform:
```bash
$ tns platform update android
```

**Comment by gggiii** [comment] 2018-12-04 17:12
@mhlulani worked for me too, thanks

**Comment by gkumar414** [comment] 2019-01-31 11:55
Run the following command, it is ok..
tns platform update android

**Comment by Sunhat** [comment] 2020-08-10 04:05
18 months and still no real solution

**Comment by SzaboKrisztian** [comment] 2020-08-11 09:14
This is still an issue. I have tried pretty much all the above suggested solutions, but none works for me, neither in the existing project that I'd like to include it in, nor in a brand new blank project. Library version that I'm using are as follows:

```
"dependencies": {
    "@angular/animations": "~9.1.0",
    "@angular/common": "~9.1.0",
    "@angular/compiler": "~9.1.0",
    "@angular/core": "~9.1.0",
    "@angular/forms": "~9.1.0",
    "@angular/platform-browser": "~9.1.0",
    "@angular/platform-browser-dynamic": "~9.1.0",
    "@angular/router": "~9.1.0",
    "@auth0/angular-jwt": "~5.0.1",
    "@nativescript/angular": "~9.0.0",
    "@nativescript/theme": "~2.3.0",
    "@types/jest": "^26.0.9",
    "nativescript-toast": "^2.0.0",
    "nativescript-ui-sidedrawer": "^9.0.2",
    "ngx-webstorage": "~6.0.0",
    "reflect-metadata": "~0.1.12",
    "rxjs": "^6.5.0",
    "tns-core-modules": "~6.5.0",
    "zone.js": "~0.10.3"
  }
```
