### ISSUE TITLE
fillColor not updating to view when change 

### ISSUE THREAD

**Issue by giorgi-abashidze** [telerik/nativescript-ui-feedback#677] opened 2018-05-28 11:18 UTC
I'm changing indicatorStyle.fillcolor from javascript and fillColor not changing in view it staus same as loaded. when I log indicatorStyle.fillcolor, the color is changed in javascript.

**Comment by tsonevn** [comment] 2018-06-06 10:04
Duplicate of #639

**Closed by tsonevn** 2018-06-06 10:04 UTC
