### ISSUE TITLE
How to hide scroll indicator in horizontal scroll radlistview nativescript angular?

### ISSUE THREAD

**Issue by ArigarasuthanRepo** [telerik/nativescript-ui-feedback#1007] opened 2019-02-06 07:49 UTC
Iam working application for android and ios.Iam using radlistview for showing list items horizontally.While scrolling horizontally the scroll indicator was not hide in ios platform but in android it was hide.How to fix the issue for ios?

**Comment by tsonevn** [comment] 2019-02-14 07:26
Duplicate of https://github.com/telerik/nativescript-ui-feedback/issues/752

**Closed by tsonevn** 2019-02-14 07:26 UTC
