### ISSUE TITLE
The "index" of elements in all events is incorrect if grouping, filtering and/or sorting is enabled

### ISSUE THREAD

**Issue by VladimirAmiorkov** [telerik/nativescript-ui-feedback#804] opened 2018-08-23 14:28 UTC
Inside the following events:
- itemSelecting
- itemSelected
- itemDeselecting
- itemDeselected
- itemReorderStarting
- itemReorderStarted
- itemReordered
- itemHold
- loadMoreDataRequested
- itemTap

**Comment by zbranzov** [comment] 2018-08-31 11:57
The issue is already fixed in nativescript-ui-listview@3.6.1. Enjoy!

**Closed by zbranzov** 2018-08-31 11:57 UTC
Labels: listview, ready for release

**Comment by MopheusDG** [comment] 2018-09-02 21:42
Hi, I've update to nativescript-ui-listview@3.6.1 and I still do get index 0 after a group separator is added or a filter applied. Do I need to update anything else ?

My tested behaviour is apply FILTER via SearchBar and then, itemSelected gets args.index 0 for the first filtered item instead of the right index of the item.

Ideas ? Thanks.

**Comment by MopheusDG** [comment] 2018-09-02 22:30
NVM, I had to remove platform, add platform and make a full rebuild, but seems to be working now.... not sure why, but mostly add/remove is just enough. Sorry.

I'll keep testing but seems to be ok with 3.6.1, thanks !
