### ISSUE TITLE
[Feature Request] make it possible to disable a date in RadCalendar

### ISSUE THREAD

**Issue by DevPlus31** [telerik/nativescript-ui-feedback#960] opened 2018-12-07 16:32 UTC
Hello, 

Currently it's not possible to disable date please consider to add this feature in future version.
if you have any idea how to counter this issue it's welcome. 

Thanks.

**Comment by tsonevn** [comment] 2018-12-11 12:14
Duplicate of https://github.com/telerik/nativescript-ui-feedback/issues/556

**Closed by tsonevn** 2018-12-11 12:14 UTC
