### ISSUE TITLE
Modal dialog fails  on IOS

### ISSUE THREAD

**Issue by wanpeng2008** [telerik/nativescript-ui-feedback#760] opened 2018-07-30 14:26 UTC
I try to open a modal dialog which contains a RadDataForm, but get following error msg on IOS
````
Error: Uncaught (in promise): TypeError: null is not an object (evaluating 'this.page.ios')
````
The error is clear after RadDataForm being removed from the modal dialog.

On Android, all is ok.

Please see https://play.nativescript.org/?template=play-ng&id=geYYJx&v=20

**Comment by NickIliev** [comment] 2018-07-31 10:37
Hey @wanpeng2008 the issue is related [to this known bug](https://github.com/telerik/nativescript-ui-feedback/issues/690) which was addressed and resolved via [this PR](https://github.com/NativeScript/nativescript-ui-dataform/pull/23).

The fix will be included in the next official release of nativescript-ui-dataform.

**Closed by NickIliev** 2018-07-31 10:37 UTC
