### ISSUE TITLE
 The 'index' from 'ListViewEventData' of the swipe action events is not correct while using 'groupingFunction'

### ISSUE THREAD

**Issue by tigrenok00** [telerik/nativescript-ui-feedback#789] opened 2018-08-13 12:47 UTC
Hi,

The ListViewEventData which holds the args for swipe events has an **index** property which I was using to find the corresponding object in the data source.
However, since I started using ListView grouping function, I see that I can no longer do it because the index relates to the order of the item as it is displayed on the screen, and more than that, it actually includes the group headers in the count as well.
Is this a bug? If not, how can I access the item in the data source which the event is fired on?

I'm on version 3.5.11.

Thanks,
Maria

**Comment by VladimirAmiorkov** [comment] 2018-08-13 13:02
If you could provide a runnable sample project that reproduces this issue it would be of a great help.

**Comment by VladimirAmiorkov** [comment] 2018-08-13 13:02
Also could you share more details on which platforms and what versions of core modules, runtimes etc. are you using?

**Comment by tigrenok00** [comment] 2018-08-13 13:07
@VladimirAmiorkov 
Hi, I'm not able to share the original project and currently don't have the time to create a side project to reproduce this. Given the fact that 3 people mentioned the same thing in this issue https://github.com/telerik/nativescript-ui-feedback/issues/596 and had no replies, I would appreciate if you could check this on your side.

**Comment by tigrenok00** [comment] 2018-08-13 13:09
I'm currently on android,

"tns-android": {
      "version": "4.1.3"
    }
"nativescript-angular": "^6.0.6",
"tns-core-modules": "4.1.1"

Please let me know if I can provide anything else, except of a running project.

**Comment by VladimirAmiorkov** [comment] 2018-08-16 14:56
Hi @tigrenok00 ,

As @NickIliev mentioned in the other thread this issue has been resolved and is no longer observed in the latest version 3.5.11 which is why we are prompting you or anyone else that observes such issue to send as a sample project. You can use the [playground](https://play.nativescript.org) if it is easier for you.

I just tested our official demo angular application located [here](https://github.com/telerik/nativescript-ui-samples-angular/tree/master/listview) and using the "Data Operations > Multiple operations" example and looking at the values provided by the `ListViewEventData` the `index` represents the correct item after any of the data operations are enabled or disabled. I am attaching a short video of the observed behaviour on our side, if you could provide anymore information that could be project specific and is different than our demo code please let me know.
![data operations index test](https://user-images.githubusercontent.com/4989411/44216365-69094800-a17d-11e8-8e78-8331495f2f66.gif)

**Comment by tigrenok00** [comment] 2018-08-16 15:06
@VladimirAmiorkov 
Hi Vladimir,
The example shows the tap event, however, the problem I observe is within the args.index of the **swipe** events. Perhaps you could combine in you testing environment the example of the swipe actions on listview and add a grouping function, and see if the index you're getting is correct - in our case, it isn't. Perhaps the fix wasn't made for the swipe events specifically... Thank you!

**Comment by VladimirAmiorkov** [comment] 2018-08-16 16:05
@tigrenok00 Thank you for clarifying that out. I will take a look and let you know when I have more details to share. I edited the title to better illustrate the issue at hand.

**Comment by VladimirAmiorkov** [comment] 2018-08-23 14:39
Hi @tigrenok00 ,

I have managed to observe the described issue in all RadListView events that provide an `index`. The good news is that it is fixed and currently being review and tested, we hope to have a new version released as soon as possible. Look out for the next version.

**Comment by tigrenok00** [comment] 2018-08-23 15:41
@VladimirAmiorkov 
Thank you so much!

**Comment by zbranzov** [comment] 2018-08-31 11:57
The issue is already fixed in nativescript-ui-listview@3.6.1. Enjoy!

**Closed by zbranzov** 2018-08-31 11:57 UTC
Labels: listview, ready for release, severity: high
