### ISSUE TITLE
AutoCompleteInline in RadDataForm triggers propertyCommitted on init with empty value

### ISSUE THREAD

**Issue by wendt88** [telerik/nativescript-ui-feedback#524] opened 2018-02-12 15:20 UTC
trying sample: https://github.com/telerik/nativescript-ui-samples-angular under "DataForm" -> "Editors" -> "AutoComplete"
AutoCompleteInline editor with `autoCompleteDisplayMode="tokens"` triggers the `propertyCommitted` event of its `RadDataForm`, but `args.entityProperty.value` is an empty array, also on clicking "Check values"

**Comment by tsonevn** [comment] 2018-02-14 06:50
Hi @wendt88,
Thank you for contacting us.
I was able to recreate this issue only on Android, for it seems to work as expected. Is this correct or you can recreate the problem on iOS as well?

**Comment by wendt88** [comment] 2018-02-19 10:27
on iOS works fine, thats right

**Comment by tgpetrov** [comment] 2018-10-16 12:04
This issue is a duplicate of [this issue](https://github.com/telerik/nativescript-ui-feedback/issues/738).

**Closed by tgpetrov** 2018-10-16 12:04 UTC
Labels: backlog, bug, dataform, severity: medium
