### ISSUE TITLE
Autocomplete: unrecognized selector sent to instance

### ISSUE THREAD

**Issue by terreb** [telerik/nativescript-ui-feedback#605] opened 2018-04-03 10:42 UTC
### Did you verify this is a real problem by searching the [NativeScript Forum](https://discourse.nativescript.org/)?
Yes

### Tell us about the problem
When navigating to a view with autocomplete on iOS the app crashes. In the console I see "[SuggestionViewDataSourceImpl listView:numberOfItemsInSection:]: unrecognized selector sent to instance 0x7feae202a9c0"

### Which platform(s) does your issue occur on?
iOS

### Please provide the following version numbers that your issue occurs with:
cli: 3.4.1
tns-core-modules: 3.4.1
tns-ios: 3.4.1
nativescript-ui-autocomplete: 3.5.0/3.6.0

### Please tell us how to recreate the issue in as much detail as possible.
Please clone, build and run the app from https://github.com/terreb/autocmp. The app itself is very basic example from nativescript-ui-samples. I also added all plugins I have in my real app. I suspect this might happen because of one of those plugins. Unfortunately I haven't managed to figure out the exact cause. You should see the error message right after startup.

PS: if using autocomplete from nativescript-pro-ui/autocomplete it works fine, but I would like to use the individual component nativescript-ui-autocomplete because of 2 reasons: 1. the bundled version is getting deprecated, 2. that version has bugs on Android and unusable for me. I also tried to install both plugins in the same time and use the old for iOS and new for Android, but having them simultaneously seems to cause other bugs in the app.

### Is there code involved? If so, please share the minimal amount of code needed to recreate the problem.
Please see above

**Comment by terreb** [comment] 2018-04-03 13:58
I gathered a bit more info today, the app crashes on simulator only. On real device it works. The error message I mentioned above appears on iOS 9.3 simulator, on iOS 11.2 the app crashes without any messages in js console.

**Comment by tsonevn** [comment] 2018-04-10 09:05
Hi @terreb,
I tested the AutoComplete component with the [nativescript-ui-samples](https://github.com/telerik/nativescript-ui-samples) project and was unable to recreate this problem.
The problem in your project might be related to the custom entitlements, which you have added to the App_Resources/iOS folder.

**Comment by terreb** [comment] 2018-04-11 11:16
Hi @tsonevn, thanks for the answer. Have you tried with the repo I provided? As soon as I switch to the bundled nativescript-pro-ui plugin the issue is gone, but the bundled plugin is getting deprecated, so I would like to use the individual one.

**Comment by tgpetrov** [comment] 2018-10-19 12:01
@terreb I checked you repo, it seems like you have referenced an old version of `nativescript-imagepicker` that depends on `nativescript-pro-ui` causing a duplicate of the autocomplete. You need to update the image picker to at least [5.0.0](https://github.com/NativeScript/nativescript-imagepicker/releases/tag/v5.0.0). You also need to update the `nativescript-ui-sidedrawer` to at least [4.0.0](https://github.com/telerik/nativescript-ui-feedback/blob/master/releases/sidedrawer.md#v400) to avoid conflicting dependencies. Let me know if your issue is resolved.

**Comment by tgpetrov** [comment] 2018-11-30 14:52
We'll consider this thread closed, feel free to write back if you reproduce the issue again.

**Closed by tgpetrov** 2018-11-30 14:52 UTC
Labels: autocomplete, needs more info
