### ISSUE TITLE
[Android] RadListView reorder crashes when starting reorder then dropping in the same place

### ISSUE THREAD

**Issue by vcooley** [telerik/nativescript-ui-feedback#322] opened 2017-10-03 14:57 UTC
On Android, starting a reorder by grabbing a list item, then immediately dropping it causes a crash. This appears to only happen if the list has not been reordered yet. It also does not appear to happen if the item is dragged from its original position then dropped in its original position.

I observed this issue when testing on the angular sample app. To reproduce, clone and run the sample app. Then go to item reorder or item reorder with handle, start to drag an item, but drop it in the same place instead of reordering.

**Comment by marcelomiranda90** [comment] 2017-10-04 23:12
Same problem here. Using reorderMode = "Drag" does not happen the error, it is an alternative while the problem is not solved, however HoldandDrag is much more charming for the user.

**Comment by marcelomiranda90** [comment] 2017-10-05 12:30
![ezgif com-video-to-gif](https://user-images.githubusercontent.com/30594073/31227234-822cf186-a9af-11e7-9d6e-1aa1aea35ba4.gif)

This error is caused by cloning the nativescript-ui-pro-sample angular version, in the non-angular sdk the error does not appear to occur.
Important that the example be done before any other reordering, as soon as the radlistview is loaded for the first time.

If you need any other information, I'll be happy to help.

Thank you.

**Comment by Natalia-Hristova** [comment] 2017-10-05 13:33
Hi @vcooley and @marcelomiranda90 ,
I can confirm that this indeed happens and will be logged as a bug.

Thanks for the given info. Even though it was enough to reproduce the issue (this time) for further issues I would ask you to use the "issue template" because the detailed information saves your, other users and team's time.Thanks for your understanding. : )

Regards, 
Natalia

**Comment by marcelomiranda90** [comment] 2017-10-05 13:36
Thanks @Natalia-Hristova ;)

**Comment by VladimirAmiorkov** [comment] 2017-11-20 11:23
Hi @marcelomiranda90 ,

We are working on resolving this issue and a fix for it is already available in our next version. If you would like to test it simply target the _"next"_ version by changing the version reference in your package.json to `nativescript-pro-ui:"next"`

**Comment by Natalia-Hristova** [comment] 2017-11-30 11:46
Fixed in `next` version. Will be available in the next official version of the plugin.

**Closed by Natalia-Hristova** 2017-11-30 11:46 UTC
Labels: backlog, bug, in review, listview, S:Critical
