### ISSUE TITLE
RadListView issue after minimizing application

### ISSUE THREAD

**Issue by tigrenok00** [telerik/nativescript-ui-feedback#221] opened 2017-06-26 14:59 UTC
Hi,
I have a horizontal listview with a button in the template.
The button has a tap event, which works fine. The problem is, that after minimizing application and then going back to it, the buttons' tap event does not rize when tapped. After reloading the component again it works fine. The rest of the screen works fine, the only issue is with the buttons inside the listview.

I've tried replacing the radListView with a scroll view and ngFor for the buttons, and the issue doesn't happen that way (attaching both pieces of code):

```
<RadListView row="3" *ngIf="this.orderCartModeSw || this.assortmentModeSw || this.viewOrderModeSw" #catListView tkExampleTitle
        tkToggleNavButton [items]="categories">
        <ng-template tkListItemTemplate let-item="item">

            <Button class="category-btn-default"
            [class.category-btn-selected]="isCategorySelected(item)" 
            (tap)="onCategorySelectedBtn(item)" text="{{item.orderCategoryDescr}} [{{countItemsInCategory(item)}}]"></Button>
        
        </ng-template>
        <ListViewLinearLayout tkListViewLayout scrollDirection="Horizontal"></ListViewLinearLayout>
    </RadListView>

```

```

<StackLayout orientation="horizontal" row="3" *ngIf="this.orderCartModeSw || this.assortmentModeSw || this.viewOrderModeSw">
        <ScrollView orientation="horizontal">
            <StackLayout orientation="horizontal">
                <Button *ngFor="let item of categories" class="category-btn-default" [class.category-btn-selected]="isCategorySelected(item)"
                    (tap)="onCategorySelectedBtn(item)" text="{{item.orderCategoryDescr}} [{{countItemsInCategory(item)}}]"></Button>
            </StackLayout>
        </ScrollView>
    </StackLayout>

```

Which platform(s) does your issue occur on?
Android

Please provide the following version numbers that your issue occurs with:
CLI: 3.0.1
Cross-platform modules: 3.0.0
Runtime(s): 3.0.0
Plugin(s): "nativescript-telerik-ui": "2.0.1"

**Comment by ginev** [comment] 2017-06-27 11:33
@tigrenok00 can you please try reproducing the issue with the the @next version of nativescript-telerik-ui instead of 2.0.1? We have addressed a similar issue in our internal codebase which will be released as a part of the upcoming 3.0.0 version of NS UI. Please make sure to delete the platforms folder after installing the @next version.

Thanks.

**Comment by tigrenok00** [comment] 2017-06-27 12:13
@ginev Hi, it indeed is fine in the @next version. When is it due to be released? Can we stay on this build until then, how stable is it?
Thank you!

**Comment by ginev** [comment] 2017-06-27 12:37
@tigrenok00 I suggest you wait for the official release which is due to a couple of days (by the end of the week). The @next version simply verifies that the fix we have introduced is relevant to your issue.

Stay tuned for official announcement on nativescript.org.

Thanks for your patience!

**Closed** 2017-06-27 13:24 UTC
Labels: listview
