### ISSUE TITLE
Autocomplete TokenModel is add  only two values ,how can i add multiple values add in TokenModel

### ISSUE THREAD

**Issue by yogapriyaK** [telerik/nativescript-ui-feedback#882] opened 2018-10-17 08:15 UTC
Autocomplete TokenModel is add  only two values ,how can i add multiple values add in TokenModel

**Comment by progressify** [comment] 2018-12-19 16:33
I think he means: the only value accepted by TokenModel is a string. 
Can be comfortable store in TokenModel an Object, for example

**Comment by tgpetrov** [comment] 2019-02-22 08:12
Closing as a duplicate of https://github.com/telerik/nativescript-ui-feedback/issues/65

**Closed by tgpetrov** 2019-02-22 08:12 UTC
Labels: question
