### ISSUE TITLE
SideDrawer Angular over UI dialogs when using showOverNavigation

### ISSUE THREAD

**Issue by davorpeic** [telerik/nativescript-ui-feedback#61] opened 2017-02-19 22:15 UTC
Hi,

using latest NS 2.5, nativescript-ui 1.6, iOS

I have sideDrawer showing "logout" button, when pressed I'm showing confirm dialog and in combination with drawer attribute showOverNavigation=true, the dialog goes under the drawer. When I don't show drawer over navigation, then the dialog is presented correct.

I also tried to close drawer before showing dialog, but dialog shows up and then hides, I guess layout change triggers that.

![glass](https://cloud.githubusercontent.com/assets/694091/23107209/933833a4-f6be-11e6-978d-bc1b4400fdee.png)

thanks

**Comment by mn-martin** [comment] 2017-03-01 16:10
I'm having the same issue

**Comment by davorpeic** [comment] 2017-03-01 16:12
This is only possible to activate on iOS, and I actually ended up disabling showOverNavigation because after I press "ok" on alert under, is messes up all ui components so tabs stop working and drawer to, and eventually app crashes, no errors thou. I guess this feature is available but not fully tested.

**Comment by mn-martin** [comment] 2017-03-01 16:23
How did you disable it?

```typescript
export function navigatingTo(args: EventData) {
    let page = args.object as DrawerPage;

    if (isIOS) {
        // Make the iOS status bar appear white on transparent
        let navigationBar = topmost().ios.controller.navigationBar;
        navigationBar.barStyle = UIBarStyle.BlackTranslucent;

        let sideDrawer: RadSideDrawer = page.sideDrawer;
        sideDrawer.showOverNavigation = false;
    }
}
```

The above code actually didn't solve the problem for me. (there's now a ~20px margin on the bottom of my drawer thought, but the dialog issues stay the same)

(I'd prefer to not change my android app appearance as well)

**Comment by davorpeic** [comment] 2017-03-01 16:26
Well, if you don't set that parameter, default is false, but you can alter that value setting the value in component
```
showOverNavigation:boolean = false; 

ngOnInit() {
        if(application.ios) {
            this.showOverNavigation = false; // or true
        }
}
```

and then applying it depending on the platform
```
<RadSideDrawer tkExampleTitle tkToggleNavButton transition="SlideInOnTopTransition" [showOverNavigation]="showOverNavigation">
...
```

**Comment by mn-martin** [comment] 2017-03-02 08:24
@davorpeic Unfortunately your solution is giving me the same result as my code did.

How does your XML file look like?

* [Getting started](https://github.com/telerik/nativescript-ui-samples/blob/release/sdk/app/sidedrawer/getting-started/getting-started.xml)
* [Drawer over navigation](https://github.com/telerik/nativescript-ui-samples/blob/release/sdk/app/sidedrawer/over-navigation/drawer-over-navigation.xml)

> Drawer over navigation is how mine does look like.

**Comment by davorpeic** [comment] 2017-03-02 13:47
I'm working with angular version so my drawer follows this template
https://github.com/telerik/nativescript-ui-samples-angular/blob/release/sdkAngular/app/sidedrawer/getting-started/getting-started.component.html

But theirs is based on the core docs http://docs.telerik.com/devtools/nativescript-ui/Controls/Angular/SideDrawer/getting-started

**Comment by mn-martin** [comment] 2017-03-03 14:18
@davorpeic Ah ok, that seems to be the reason then. Thank you for clarification 👍

**Comment by mn-martin** [comment] 2017-03-08 11:00
I wanted to note that after several attempts I'm still unable to use the SideDrawer without showOverNavigation. I'm using TypeScript and followed the samples. I think the docs need an update? 

Also it doesn't seem to be possible to know if the SideDrawer is currently visible. 

The Events onDrawerClosingEvent & onDrawerOpening won't fire on Slide Gestures. Also it doesn't seem to be possible attaching a gesture event listener to the page content because that would disable user interactivity for any buttons and stuff. Therefore we cannot tell if someone is currently sliding out the SideDrawer. (The issue with dialogs would also occur if it's in the middle of a sliding transition)

This makes my app crashable via push notifications while the user is opening the SlideDrawer and I cannot delay the Dialog because I don't know whats going on with the drawer.

**Comment by VladimirAmiorkov** [comment] 2017-03-14 15:56
Hi all,

Currently the "show over navigation bar" feature of the RadSideDrawer is not supported in {N} + Angular. We have been working on this feature and it is planned for official release with the next major version of the nativescript-telerik-ui plugin. You can expect it in the middle of next month.

You can test this feature in our "next" tag of the plugin by doing `tns plugin add nativescript-telerik-ui@next`

Disclamer: Note that the "next" version of the plugin is considered unstable because it is updated daily even hourly by the nativescript-telerik-ui team which is why it is not recommended to be used in a production project. Its main goal is to provide you with an immediate way to verify bug fixes and new features.

**Comment by davorpeic** [comment] 2017-03-14 16:28
Thanks for the update @VladimirAmiorkov

**Comment by mn-martin** [comment] 2017-03-15 08:04
Yes, thanks indeed @VladimirAmiorkov 👍

**Comment by VladimirAmiorkov** [comment] 2017-05-04 11:12
This feature has been implemented in nativescript-telerik-ui version "^2.0.0"

**Comment by VladimirAmiorkov** [comment] 2018-03-20 15:38
Reopened due to this issue still being reproducible with latest nativescript-ui-sidedrawer: "3.5.1"

**Comment by VladimirAmiorkov** [comment] 2018-03-20 15:57
This issue will be resolved with the upcoming 4.0.0 release of NativeScript and the nativescript-ui-sidedrawer plugin.

**Comment by audaciousanil** [comment] 2018-03-23 23:54
We are using nativescript-angular 5.1 components in our NativeScript (3.4.3) mobile app and the issue is observed in iOS.

![image](https://user-images.githubusercontent.com/21695372/37857725-f9c28ec8-2ed3-11e8-9b5f-d3404a41bd79.png)

**Comment by VladimirAmiorkov** [comment] 2018-03-24 06:59
Hi @audaciousanil ,

As mentioned above this issue will be resolved once the 4.0.0 release is available for both NativeScript and nativescript-ui-sidedrawer.

**Closed** 2018-04-10 15:47 UTC
Labels: angular, backlog, bug, ready for release, severity: low, sidedrawer

**Comment by balachandran1988** [comment] 2018-04-12 11:51
Hi @davorpeic  , can u pls provide solution for this.

**Comment by davorpeic** [comment] 2018-04-12 13:36
Hi @balachandran1988, please check Vladimir's response before closing this issue.
