### ISSUE TITLE
memory leak in nativescipt-ui-listview(RadListView)

### ISSUE THREAD

**Issue by kazemihabib** [telerik/nativescript-ui-feedback#46] opened 2017-01-13 17:07 UTC
Here is a sample project I created https://github.com/kazemihabib/nativescript-telerik-ui-memory-leak
when I use telerik ui nativescript listView the memory increases steadly with out even touching the screen of device .

![first](https://cloud.githubusercontent.com/assets/10830552/21938272/dfe811d0-d9cf-11e6-80a6-5bc88b8a93ed.png)

and after a while 

![second](https://cloud.githubusercontent.com/assets/10830552/21938299/fa1181ae-d9cf-11e6-9d48-84d0f02c8d36.png)
it will increase with out stopping and after a while, it will be killed and closed.

but when I use nativescript default listview this is  not happens.

**Comment by kazemihabib** [comment] 2017-01-18 20:42
any update on this?

**Comment by ginev** [comment] 2017-01-26 11:10
@kazemihabib this is already fixed and is due to be released on the upcoming version of NativeScript UI.

**Comment by eduardoturconi** [comment] 2017-01-28 17:34
@ginev is this fixed in `@next`?

I tried using nativescript-telerik-ui@1.6.0-2017.1.27.2 and I'm still having memory leak.

**Comment by ginev** [comment] 2017-02-01 13:46
@eduardoturconi the issue is fixed in the release candidate branch and thus not uploaded with @next. We will release NativeScript UI 1.6 today and you will be able to download the fixed version. I guess it is a good idea to also create a @rc upload.

**Comment by kazemihabib** [comment] 2017-02-02 21:05
thanks @ginev the problem of memory leak fixed in new version.
but in new version when the app starts(not resume) when I tap on item for first time it takes 4 seconds to be selected then for other taps it works smoothly.
@eduardoturconi do you have this problem with the new version?

**Comment by ginev** [comment] 2017-03-06 15:14
@kazemihabib please feel free to open a new issue if you think there is a problem.

**Closed by ginev** 2017-03-06 15:14 UTC
Labels: listview
